### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel
  id: IBindingModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel.BindingInfo
  langs:
  - csharp
  - vb
  name: IBindingModel
  nameWithType: IBindingModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IBindingModel.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: IBindingModel
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IBindingModel.cs
    startLine: 7
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  syntax:
    content: public interface IBindingModel
    content.vb: Public Interface IBindingModel
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel.BindingInfo
  commentId: P:Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel.BindingInfo
  id: BindingInfo
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel
  langs:
  - csharp
  - vb
  name: BindingInfo
  nameWithType: IBindingModel.BindingInfo
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel.BindingInfo
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IBindingModel.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: BindingInfo
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IBindingModel.cs
    startLine: 9
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  syntax:
    content: BindingInfo BindingInfo { get; set; }
    parameters: []
    return:
      type: BindingInfo
    content.vb: Property BindingInfo As BindingInfo
  overload: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel.BindingInfo*
  modifiers.csharp:
  - get
  - set
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel.BindingInfo*
  commentId: Overload:Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel.BindingInfo
  isExternal: false
  name: BindingInfo
  nameWithType: IBindingModel.BindingInfo
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IBindingModel.BindingInfo
- uid: BindingInfo
  isExternal: true
  name: BindingInfo
  nameWithType: BindingInfo
  fullName: BindingInfo
shouldSkipMarkup: true
