### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  commentId: T:Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  id: ApplicationType
  parent: Microsoft.AspNetCore.Server.IntegrationTesting
  children:
  - Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType.Portable
  - Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType.Standalone
  langs:
  - csharp
  - vb
  name: ApplicationType
  nameWithType: ApplicationType
  fullName: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  type: Enum
  source:
    remote:
      path: src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/ApplicationType.cs
      branch: dev
      repo: https://github.com/aspnet/hosting
    id: ApplicationType
    path: src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/ApplicationType.cs
    startLine: 5
  assemblies:
  - Microsoft.AspNetCore.Server.IntegrationTesting
  namespace: Microsoft.AspNetCore.Server.IntegrationTesting
  syntax:
    content: public enum ApplicationType
    content.vb: Public Enum ApplicationType
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType.Portable
  commentId: F:Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType.Portable
  id: Portable
  parent: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  langs:
  - csharp
  - vb
  name: Portable
  nameWithType: ApplicationType.Portable
  fullName: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType.Portable
  type: Field
  source:
    remote:
      path: src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/ApplicationType.cs
      branch: dev
      repo: https://github.com/aspnet/hosting
    id: Portable
    path: src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/ApplicationType.cs
    startLine: 7
  assemblies:
  - Microsoft.AspNetCore.Server.IntegrationTesting
  namespace: Microsoft.AspNetCore.Server.IntegrationTesting
  syntax:
    content: Portable = 0
    return:
      type: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType.Standalone
  commentId: F:Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType.Standalone
  id: Standalone
  parent: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  langs:
  - csharp
  - vb
  name: Standalone
  nameWithType: ApplicationType.Standalone
  fullName: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType.Standalone
  type: Field
  source:
    remote:
      path: src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/ApplicationType.cs
      branch: dev
      repo: https://github.com/aspnet/hosting
    id: Standalone
    path: src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/ApplicationType.cs
    startLine: 8
  assemblies:
  - Microsoft.AspNetCore.Server.IntegrationTesting
  namespace: Microsoft.AspNetCore.Server.IntegrationTesting
  syntax:
    content: Standalone = 1
    return:
      type: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.AspNetCore.Server.IntegrationTesting
  commentId: N:Microsoft.AspNetCore.Server.IntegrationTesting
  isExternal: false
  name: Microsoft.AspNetCore.Server.IntegrationTesting
  nameWithType: Microsoft.AspNetCore.Server.IntegrationTesting
  fullName: Microsoft.AspNetCore.Server.IntegrationTesting
- uid: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  commentId: T:Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
  parent: Microsoft.AspNetCore.Server.IntegrationTesting
  isExternal: false
  name: ApplicationType
  nameWithType: ApplicationType
  fullName: Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationType
