### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.IDesignTimeMvcBuilderConfiguration
  commentId: T:Microsoft.AspNetCore.Mvc.IDesignTimeMvcBuilderConfiguration
  id: IDesignTimeMvcBuilderConfiguration
  parent: Microsoft.AspNetCore.Mvc
  children:
  - Microsoft.AspNetCore.Mvc.IDesignTimeMvcBuilderConfiguration.ConfigureMvc(Microsoft.Extensions.DependencyInjection.IMvcBuilder)
  langs:
  - csharp
  - vb
  name: IDesignTimeMvcBuilderConfiguration
  nameWithType: IDesignTimeMvcBuilderConfiguration
  fullName: Microsoft.AspNetCore.Mvc.IDesignTimeMvcBuilderConfiguration
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/IDesignTimeMvcBuilderConfiguration.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: IDesignTimeMvcBuilderConfiguration
    path: src/Microsoft.AspNetCore.Mvc.Core/IDesignTimeMvcBuilderConfiguration.cs
    startLine: 11
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc
  summary: "\nConfigures the <see cref=\"T:Microsoft.Extensions.DependencyInjection.IMvcBuilder\"></see>. Implement this interface to enable design-time configuration\n(for instance during pre-compilation of views) of <see cref=\"T:Microsoft.Extensions.DependencyInjection.IMvcBuilder\"></see>.\n"
  example: []
  syntax:
    content: public interface IDesignTimeMvcBuilderConfiguration
    content.vb: Public Interface IDesignTimeMvcBuilderConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.IDesignTimeMvcBuilderConfiguration.ConfigureMvc(Microsoft.Extensions.DependencyInjection.IMvcBuilder)
  commentId: M:Microsoft.AspNetCore.Mvc.IDesignTimeMvcBuilderConfiguration.ConfigureMvc(Microsoft.Extensions.DependencyInjection.IMvcBuilder)
  id: ConfigureMvc(Microsoft.Extensions.DependencyInjection.IMvcBuilder)
  parent: Microsoft.AspNetCore.Mvc.IDesignTimeMvcBuilderConfiguration
  langs:
  - csharp
  - vb
  name: ConfigureMvc(IMvcBuilder)
  nameWithType: IDesignTimeMvcBuilderConfiguration.ConfigureMvc(IMvcBuilder)
  fullName: Microsoft.AspNetCore.Mvc.IDesignTimeMvcBuilderConfiguration.ConfigureMvc(Microsoft.Extensions.DependencyInjection.IMvcBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/IDesignTimeMvcBuilderConfiguration.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: ConfigureMvc
    path: src/Microsoft.AspNetCore.Mvc.Core/IDesignTimeMvcBuilderConfiguration.cs
    startLine: 17
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc
  summary: "\nConfigures the <see cref=\"T:Microsoft.Extensions.DependencyInjection.IMvcBuilder\"></see>.\n"
  example: []
  syntax:
    content: void ConfigureMvc(IMvcBuilder builder)
    content.vb: Sub ConfigureMvc(builder As IMvcBuilder)
    parameters:
    - id: builder
      type: Microsoft.Extensions.DependencyInjection.IMvcBuilder
      description: The <see cref="T:Microsoft.Extensions.DependencyInjection.IMvcBuilder"></see>.
references:
- uid: Microsoft.AspNetCore.Mvc
  commentId: N:Microsoft.AspNetCore.Mvc
  isExternal: false
  name: Microsoft.AspNetCore.Mvc
  nameWithType: Microsoft.AspNetCore.Mvc
  fullName: Microsoft.AspNetCore.Mvc
- uid: Microsoft.Extensions.DependencyInjection.IMvcBuilder
  commentId: T:Microsoft.Extensions.DependencyInjection.IMvcBuilder
  parent: Microsoft.Extensions.DependencyInjection
  isExternal: false
  name: IMvcBuilder
  nameWithType: IMvcBuilder
  fullName: Microsoft.Extensions.DependencyInjection.IMvcBuilder
- uid: Microsoft.Extensions.DependencyInjection
  commentId: N:Microsoft.Extensions.DependencyInjection
  isExternal: false
  name: Microsoft.Extensions.DependencyInjection
  nameWithType: Microsoft.Extensions.DependencyInjection
  fullName: Microsoft.Extensions.DependencyInjection
