### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  id: MemoryConfigurationSource
  parent: Microsoft.Extensions.Configuration.Memory
  children:
  - Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder)
  - Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.InitialData
  langs:
  - csharp
  - vb
  name: MemoryConfigurationSource
  nameWithType: MemoryConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/MemoryConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: MemoryConfigurationSource
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/MemoryConfigurationSource.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration.Memory
  summary: "\nRepresents in-memory data as an <see cref=\"!:IConfigurationSource\"></see>.\n"
  example: []
  syntax:
    content: 'public class MemoryConfigurationSource : IConfigurationSource'
    content.vb: >-
      Public Class MemoryConfigurationSource
          Inherits IConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.InitialData
  commentId: P:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.InitialData
  id: InitialData
  parent: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  langs:
  - csharp
  - vb
  name: InitialData
  nameWithType: MemoryConfigurationSource.InitialData
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.InitialData
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/MemoryConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: InitialData
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/MemoryConfigurationSource.cs
    startLine: 15
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration.Memory
  summary: "\nThe initial key value configuration pairs.\n"
  example: []
  syntax:
    content: public IEnumerable<KeyValuePair<string, string>> InitialData { get; set; }
    parameters: []
    return:
      type: IEnumerable{KeyValuePair{System.String,System.String}}
    content.vb: Public Property InitialData As IEnumerable(Of KeyValuePair(Of String, String))
  overload: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.InitialData*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder)
  commentId: M:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: MemoryConfigurationSource.Build(IConfigurationBuilder)
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/MemoryConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Build
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/MemoryConfigurationSource.cs
    startLine: 22
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration.Memory
  summary: "\nBuilds the <xref href=\"Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider\" data-throw-if-not-resolved=\"false\"></xref> for this source.\n"
  example: []
  syntax:
    content: public IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see>.
    return:
      type: IConfigurationProvider
      description: A <xref href="Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider" data-throw-if-not-resolved="false"></xref>
    content.vb: Public Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Extensions.Configuration.Memory
  commentId: N:Microsoft.Extensions.Configuration.Memory
  isExternal: false
  name: Microsoft.Extensions.Configuration.Memory
  nameWithType: Microsoft.Extensions.Configuration.Memory
  fullName: Microsoft.Extensions.Configuration.Memory
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.InitialData*
  commentId: Overload:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.InitialData
  isExternal: false
  name: InitialData
  nameWithType: MemoryConfigurationSource.InitialData
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.InitialData
- uid: IEnumerable{KeyValuePair{System.String,System.String}}
  commentId: '!:IEnumerable{KeyValuePair{System.String,System.String}}'
  definition: IEnumerable`1
  name: IEnumerable<KeyValuePair<String, String>>
  nameWithType: IEnumerable<KeyValuePair<String, String>>
  fullName: IEnumerable<KeyValuePair<System.String, System.String>>
  nameWithType.vb: IEnumerable(Of KeyValuePair(Of String, String))
  fullName.vb: IEnumerable(Of KeyValuePair(Of System.String, System.String))
  name.vb: IEnumerable(Of KeyValuePair(Of String, String))
  spec.csharp:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: KeyValuePair`2
    name: KeyValuePair
    nameWithType: KeyValuePair
    fullName: KeyValuePair
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: KeyValuePair`2
    name: KeyValuePair
    nameWithType: KeyValuePair
    fullName: KeyValuePair
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: IEnumerable`1
  isExternal: true
  name: IEnumerable<>
  nameWithType: IEnumerable<>
  fullName: IEnumerable<>
  nameWithType.vb: IEnumerable(Of )
  fullName.vb: IEnumerable(Of )
  name.vb: IEnumerable(Of )
  spec.csharp:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
  isExternal: false
  name: MemoryConfigurationProvider
  nameWithType: MemoryConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build*
  commentId: Overload:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build
  isExternal: false
  name: Build
  nameWithType: MemoryConfigurationSource.Build
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
shouldSkipMarkup: true
