### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.IConfiguration
  commentId: T:Microsoft.Extensions.Configuration.IConfiguration
  id: IConfiguration
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  - Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  - Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  - Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  langs:
  - csharp
  - vb
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Extensions.Configuration.IConfiguration
  type: Interface
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: IConfiguration
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
    startLine: 11
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nRepresents a set of key/value application configuration properties.\n"
  example: []
  syntax:
    content: public interface IConfiguration
    content.vb: Public Interface IConfiguration
  extensionMethods:
  - Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  - Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  commentId: P:Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  id: Item(System.String)
  parent: Microsoft.Extensions.Configuration.IConfiguration
  langs:
  - csharp
  - vb
  name: Item[String]
  nameWithType: IConfiguration.Item[String]
  fullName: Microsoft.Extensions.Configuration.IConfiguration.Item[System.String]
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: this[]
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
    startLine: 18
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nGets or sets a configuration value.\n"
  example: []
  syntax:
    content: string this[string key] { get; set; }
    parameters:
    - id: key
      type: System.String
      description: The configuration key.
    return:
      type: System.String
      description: The configuration value.
    content.vb: Property Item(key As String) As String
  overload: Microsoft.Extensions.Configuration.IConfiguration.Item*
  nameWithType.vb: IConfiguration.Item(String)
  modifiers.csharp:
  - get
  - set
  fullName.vb: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  name.vb: Item(String)
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  id: GetSection(System.String)
  parent: Microsoft.Extensions.Configuration.IConfiguration
  langs:
  - csharp
  - vb
  name: GetSection(String)
  nameWithType: IConfiguration.GetSection(String)
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: GetSection
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
    startLine: 29
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nGets a configuration sub-section with the specified key.\n"
  remarks: "\nThis method will never return <code>null</code>. If no matching sub-section is found with the specified key,\nan empty <xref href=\"Microsoft.Extensions.Configuration.IConfigurationSection\" data-throw-if-not-resolved=\"false\"></xref> will be returned.\n"
  example: []
  syntax:
    content: IConfigurationSection GetSection(string key)
    parameters:
    - id: key
      type: System.String
      description: The key of the configuration section.
    return:
      type: Microsoft.Extensions.Configuration.IConfigurationSection
      description: The <xref href="Microsoft.Extensions.Configuration.IConfigurationSection" data-throw-if-not-resolved="false"></xref>.
    content.vb: Function GetSection(key As String) As IConfigurationSection
  overload: Microsoft.Extensions.Configuration.IConfiguration.GetSection*
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  id: GetChildren
  parent: Microsoft.Extensions.Configuration.IConfiguration
  langs:
  - csharp
  - vb
  name: GetChildren()
  nameWithType: IConfiguration.GetChildren()
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetChildren()
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: GetChildren
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
    startLine: 35
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nGets the immediate descendant configuration sub-sections.\n"
  example: []
  syntax:
    content: IEnumerable<IConfigurationSection> GetChildren()
    return:
      type: IEnumerable{Microsoft.Extensions.Configuration.IConfigurationSection}
      description: The configuration sub-sections.
    content.vb: Function GetChildren As IEnumerable(Of IConfigurationSection)
  overload: Microsoft.Extensions.Configuration.IConfiguration.GetChildren*
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  id: GetReloadToken
  parent: Microsoft.Extensions.Configuration.IConfiguration
  langs:
  - csharp
  - vb
  name: GetReloadToken()
  nameWithType: IConfiguration.GetReloadToken()
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken()
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: GetReloadToken
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfiguration.cs
    startLine: 41
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nReturns a <see cref=\"!:IChangeToken\"></see> that can be used to observe when this configuration is reloaded.\n"
  example: []
  syntax:
    content: IChangeToken GetReloadToken()
    return:
      type: IChangeToken
      description: A <see cref="!:IChangeToken"></see>.
    content.vb: Function GetReloadToken As IChangeToken
  overload: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken*
references:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  parent: Microsoft.Extensions.Configuration.ConfigurationExtensions
  definition: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  name: GetConnectionString(String)
  nameWithType: ConfigurationExtensions.GetConnectionString(String)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  parent: Microsoft.Extensions.Configuration.ConfigurationExtensions
  definition: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  name: AsEnumerable()
  nameWithType: ConfigurationExtensions.AsEnumerable()
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable()
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  isExternal: true
  name: GetConnectionString(IConfiguration, String)
  nameWithType: ConfigurationExtensions.GetConnectionString(IConfiguration, String)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration, System.String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  isExternal: false
  name: AsEnumerable(IConfiguration)
  nameWithType: ConfigurationExtensions.AsEnumerable(IConfiguration)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.Item*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfiguration.Item
  isExternal: false
  name: Item
  nameWithType: IConfiguration.Item
  fullName: Microsoft.Extensions.Configuration.IConfiguration.Item
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.IConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationSection
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationSection
  nameWithType: IConfigurationSection
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetSection*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfiguration.GetSection
  isExternal: false
  name: GetSection
  nameWithType: IConfiguration.GetSection
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetSection
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetChildren*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  isExternal: false
  name: GetChildren
  nameWithType: IConfiguration.GetChildren
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
- uid: IEnumerable{Microsoft.Extensions.Configuration.IConfigurationSection}
  commentId: '!:IEnumerable{Microsoft.Extensions.Configuration.IConfigurationSection}'
  definition: IEnumerable`1
  name: IEnumerable<IConfigurationSection>
  nameWithType: IEnumerable<IConfigurationSection>
  fullName: IEnumerable<Microsoft.Extensions.Configuration.IConfigurationSection>
  nameWithType.vb: IEnumerable(Of IConfigurationSection)
  fullName.vb: IEnumerable(Of Microsoft.Extensions.Configuration.IConfigurationSection)
  name.vb: IEnumerable(Of IConfigurationSection)
  spec.csharp:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.Extensions.Configuration.IConfigurationSection
    name: IConfigurationSection
    nameWithType: IConfigurationSection
    fullName: Microsoft.Extensions.Configuration.IConfigurationSection
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Extensions.Configuration.IConfigurationSection
    name: IConfigurationSection
    nameWithType: IConfigurationSection
    fullName: Microsoft.Extensions.Configuration.IConfigurationSection
  - name: )
    nameWithType: )
    fullName: )
- uid: IEnumerable`1
  isExternal: true
  name: IEnumerable<>
  nameWithType: IEnumerable<>
  fullName: IEnumerable<>
  nameWithType.vb: IEnumerable(Of )
  fullName.vb: IEnumerable(Of )
  name.vb: IEnumerable(Of )
  spec.csharp:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  isExternal: false
  name: GetReloadToken
  nameWithType: IConfiguration.GetReloadToken
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
- uid: IChangeToken
  isExternal: true
  name: IChangeToken
  nameWithType: IChangeToken
  fullName: IChangeToken
shouldSkipMarkup: true
