### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  id: IniConfigurationProvider
  parent: Microsoft.Extensions.Configuration.Ini
  children:
  - Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Ini.IniConfigurationSource)
  - Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.Load(System.IO.Stream)
  langs:
  - csharp
  - vb
  name: IniConfigurationProvider
  nameWithType: IniConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Ini/IniConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: IniConfigurationProvider
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Ini/IniConfigurationProvider.cs
    startLine: 21
  assemblies:
  - Microsoft.Extensions.Configuration.Ini
  namespace: Microsoft.Extensions.Configuration.Ini
  summary: "\nAn INI file based <see cref=\"!:ConfigurationProvider\"></see>.\nFiles are simple line structures (<a href=\"http://en.wikipedia.org/wiki/INI_file\">INI Files on Wikipedia</a>)\n"
  example: []
  syntax:
    content: 'public class IniConfigurationProvider : FileConfigurationProvider'
    content.vb: >-
      Public Class IniConfigurationProvider
          Inherits FileConfigurationProvider
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Ini.IniConfigurationSource)
  commentId: M:Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Ini.IniConfigurationSource)
  id: '#ctor(Microsoft.Extensions.Configuration.Ini.IniConfigurationSource)'
  parent: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  langs:
  - csharp
  - vb
  name: IniConfigurationProvider(IniConfigurationSource)
  nameWithType: IniConfigurationProvider.IniConfigurationProvider(IniConfigurationSource)
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.IniConfigurationProvider(Microsoft.Extensions.Configuration.Ini.IniConfigurationSource)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Ini/IniConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: .ctor
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Ini/IniConfigurationProvider.cs
    startLine: 27
  assemblies:
  - Microsoft.Extensions.Configuration.Ini
  namespace: Microsoft.Extensions.Configuration.Ini
  summary: "\nInitializes a new instance with the specified source.\n"
  example: []
  syntax:
    content: public IniConfigurationProvider(IniConfigurationSource source)
    parameters:
    - id: source
      type: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
      description: The source settings.
    content.vb: Public Sub New(source As IniConfigurationSource)
  overload: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.Load(System.IO.Stream)
  commentId: M:Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.Load(System.IO.Stream)
  id: Load(System.IO.Stream)
  parent: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  langs:
  - csharp
  - vb
  name: Load(Stream)
  nameWithType: IniConfigurationProvider.Load(Stream)
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.Load(System.IO.Stream)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Ini/IniConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Load
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Ini/IniConfigurationProvider.cs
    startLine: 33
  assemblies:
  - Microsoft.Extensions.Configuration.Ini
  namespace: Microsoft.Extensions.Configuration.Ini
  summary: "\nLoads the INI data from a stream.\n"
  example: []
  syntax:
    content: public override void Load(Stream stream)
    parameters:
    - id: stream
      type: System.IO.Stream
      description: The stream to read.
    content.vb: Public Overrides Sub Load(stream As Stream)
  overload: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.Load*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Extensions.Configuration.Ini
  commentId: N:Microsoft.Extensions.Configuration.Ini
  isExternal: false
  name: Microsoft.Extensions.Configuration.Ini
  nameWithType: Microsoft.Extensions.Configuration.Ini
  fullName: Microsoft.Extensions.Configuration.Ini
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.#ctor*
  commentId: Overload:Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.#ctor
  isExternal: false
  name: IniConfigurationProvider
  nameWithType: IniConfigurationProvider.IniConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.IniConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  parent: Microsoft.Extensions.Configuration.Ini
  isExternal: false
  name: IniConfigurationSource
  nameWithType: IniConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.Load*
  commentId: Overload:Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.Load
  isExternal: false
  name: Load
  nameWithType: IniConfigurationProvider.Load
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider.Load
- uid: System.IO.Stream
  commentId: T:System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.IO
  commentId: N:System.IO
  isExternal: false
  name: System.IO
  nameWithType: System.IO
  fullName: System.IO
shouldSkipMarkup: true
