### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  id: IApplicationModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel)
  langs:
  - csharp
  - vb
  name: IApplicationModelConvention
  nameWithType: IApplicationModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelConvention.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: IApplicationModelConvention
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelConvention.cs
    startLine: 15
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nAllows customization of the of the <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel\"></see>.\n"
  remarks: "\nImplementaions of this interface can be registered in <see cref=\"P:Microsoft.AspNetCore.Mvc.MvcOptions.Conventions\"></see>\nto customize metadata about the application.\n\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention\"></see> run before other types of customizations to the\nreflected model.\n"
  example: []
  syntax:
    content: public interface IApplicationModelConvention
    content.vb: Public Interface IApplicationModelConvention
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel)
  id: Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention
  langs:
  - csharp
  - vb
  name: Apply(ApplicationModel)
  nameWithType: IApplicationModelConvention.Apply(ApplicationModel)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelConvention.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: Apply
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IApplicationModelConvention.cs
    startLine: 21
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nCalled to apply the convention to the <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel\"></see>.\n"
  example: []
  syntax:
    content: void Apply(ApplicationModel application)
    content.vb: Sub Apply(application As ApplicationModel)
    parameters:
    - id: application
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
      description: The <see cref="T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel"></see>.
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ApplicationModel
  nameWithType: ApplicationModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModel
