### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
  commentId: T:Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
  id: IKeyVaultSecretManager
  parent: Microsoft.Extensions.Configuration.Azure.KeyVault
  children:
  - Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager.GetKey(Microsoft.Azure.KeyVault.Secret)
  - Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager.Load(Microsoft.Azure.KeyVault.SecretItem)
  langs:
  - csharp
  - vb
  name: IKeyVaultSecretManager
  nameWithType: IKeyVaultSecretManager
  fullName: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
  type: Interface
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Azure.KeyVault/IKeyVaultSecretManager.cs
      branch: dev
      repo: https://github.com/aspnet/configuration
    id: IKeyVaultSecretManager
    path: src/Microsoft.Extensions.Configuration.Azure.KeyVault/IKeyVaultSecretManager.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.Configuration.Azure.KeyVault
  namespace: Microsoft.Extensions.Configuration.Azure.KeyVault
  summary: "\nThe <see cref=\"T:Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager\"></see> instance used to control secret loading.\n"
  example: []
  syntax:
    content: public interface IKeyVaultSecretManager
    content.vb: Public Interface IKeyVaultSecretManager
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager.Load(Microsoft.Azure.KeyVault.SecretItem)
  commentId: M:Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager.Load(Microsoft.Azure.KeyVault.SecretItem)
  id: Load(Microsoft.Azure.KeyVault.SecretItem)
  parent: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
  langs:
  - csharp
  - vb
  name: Load(SecretItem)
  nameWithType: IKeyVaultSecretManager.Load(SecretItem)
  fullName: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager.Load(Microsoft.Azure.KeyVault.SecretItem)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Azure.KeyVault/IKeyVaultSecretManager.cs
      branch: dev
      repo: https://github.com/aspnet/configuration
    id: Load
    path: src/Microsoft.Extensions.Configuration.Azure.KeyVault/IKeyVaultSecretManager.cs
    startLine: 17
  assemblies:
  - Microsoft.Extensions.Configuration.Azure.KeyVault
  namespace: Microsoft.Extensions.Configuration.Azure.KeyVault
  summary: "\nChecks if <see cref=\"T:Microsoft.Azure.KeyVault.SecretItem\"></see> value should be retrieved.\n"
  example: []
  syntax:
    content: bool Load(SecretItem secret)
    content.vb: Function Load(secret As SecretItem) As Boolean
    parameters:
    - id: secret
      type: Microsoft.Azure.KeyVault.SecretItem
      description: The <see cref="T:Microsoft.Azure.KeyVault.SecretItem"></see> instance.
    return:
      type: System.Boolean
      description: >-
        <pre>

        <code>true</code>

        </pre> is secrets value should be loaded, otherwise <pre><code>false</code></pre>.
- uid: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager.GetKey(Microsoft.Azure.KeyVault.Secret)
  commentId: M:Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager.GetKey(Microsoft.Azure.KeyVault.Secret)
  id: GetKey(Microsoft.Azure.KeyVault.Secret)
  parent: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
  langs:
  - csharp
  - vb
  name: GetKey(Secret)
  nameWithType: IKeyVaultSecretManager.GetKey(Secret)
  fullName: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager.GetKey(Microsoft.Azure.KeyVault.Secret)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Azure.KeyVault/IKeyVaultSecretManager.cs
      branch: dev
      repo: https://github.com/aspnet/configuration
    id: GetKey
    path: src/Microsoft.Extensions.Configuration.Azure.KeyVault/IKeyVaultSecretManager.cs
    startLine: 24
  assemblies:
  - Microsoft.Extensions.Configuration.Azure.KeyVault
  namespace: Microsoft.Extensions.Configuration.Azure.KeyVault
  summary: "\nMaps secret to a configuration key.\n"
  example: []
  syntax:
    content: string GetKey(Secret secret)
    content.vb: Function GetKey(secret As Secret) As String
    parameters:
    - id: secret
      type: Microsoft.Azure.KeyVault.Secret
      description: The <see cref="T:Microsoft.Azure.KeyVault.Secret"></see> instance.
    return:
      type: System.String
      description: Configuration key name to store secret value.
references:
- uid: Microsoft.Extensions.Configuration.Azure.KeyVault
  commentId: N:Microsoft.Extensions.Configuration.Azure.KeyVault
  isExternal: false
  name: Microsoft.Extensions.Configuration.Azure.KeyVault
  nameWithType: Microsoft.Extensions.Configuration.Azure.KeyVault
  fullName: Microsoft.Extensions.Configuration.Azure.KeyVault
- uid: Microsoft.Azure.KeyVault.SecretItem
  commentId: T:Microsoft.Azure.KeyVault.SecretItem
  parent: Microsoft.Azure.KeyVault
  isExternal: true
  name: SecretItem
  nameWithType: SecretItem
  fullName: Microsoft.Azure.KeyVault.SecretItem
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Azure.KeyVault
  commentId: N:Microsoft.Azure.KeyVault
  isExternal: false
  name: Microsoft.Azure.KeyVault
  nameWithType: Microsoft.Azure.KeyVault
  fullName: Microsoft.Azure.KeyVault
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.KeyVault.Secret
  commentId: T:Microsoft.Azure.KeyVault.Secret
  parent: Microsoft.Azure.KeyVault
  isExternal: true
  name: Secret
  nameWithType: Secret
  fullName: Microsoft.Azure.KeyVault.Secret
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
