### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.IConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationSection
  id: IConfigurationSection
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.IConfigurationSection.Key
  - Microsoft.Extensions.Configuration.IConfigurationSection.Path
  - Microsoft.Extensions.Configuration.IConfigurationSection.Value
  langs:
  - csharp
  - vb
  name: IConfigurationSection
  nameWithType: IConfigurationSection
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection
  type: Interface
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSection.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: IConfigurationSection
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSection.cs
    startLine: 8
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nRepresents a section of application configuration values.\n"
  example: []
  syntax:
    content: 'public interface IConfigurationSection : IConfiguration'
    content.vb: >-
      Public Interface IConfigurationSection
          Inherits IConfiguration
  inheritedMembers:
  - Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  - Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  - Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  - Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  extensionMethods:
  - Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  - Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Extensions.Configuration.IConfigurationSection.Key
  commentId: P:Microsoft.Extensions.Configuration.IConfigurationSection.Key
  id: Key
  parent: Microsoft.Extensions.Configuration.IConfigurationSection
  langs:
  - csharp
  - vb
  name: Key
  nameWithType: IConfigurationSection.Key
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection.Key
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSection.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Key
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSection.cs
    startLine: 13
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nGets the key this section occupies in its parent.\n"
  example: []
  syntax:
    content: string Key { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Key As String
  overload: Microsoft.Extensions.Configuration.IConfigurationSection.Key*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Extensions.Configuration.IConfigurationSection.Path
  commentId: P:Microsoft.Extensions.Configuration.IConfigurationSection.Path
  id: Path
  parent: Microsoft.Extensions.Configuration.IConfigurationSection
  langs:
  - csharp
  - vb
  name: Path
  nameWithType: IConfigurationSection.Path
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection.Path
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSection.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Path
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSection.cs
    startLine: 18
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nGets the full path to this section within the <xref href=\"Microsoft.Extensions.Configuration.IConfiguration\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: string Path { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Path As String
  overload: Microsoft.Extensions.Configuration.IConfigurationSection.Path*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Extensions.Configuration.IConfigurationSection.Value
  commentId: P:Microsoft.Extensions.Configuration.IConfigurationSection.Value
  id: Value
  parent: Microsoft.Extensions.Configuration.IConfigurationSection
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: IConfigurationSection.Value
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection.Value
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSection.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Value
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSection.cs
    startLine: 23
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nGets or sets the section value.\n"
  example: []
  syntax:
    content: string Value { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Value As String
  overload: Microsoft.Extensions.Configuration.IConfigurationSection.Value*
  modifiers.csharp:
  - get
  - set
references:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  commentId: P:Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  parent: Microsoft.Extensions.Configuration.IConfiguration
  isExternal: true
  name: Item[String]
  nameWithType: IConfiguration.Item[String]
  fullName: Microsoft.Extensions.Configuration.IConfiguration.Item[System.String]
  nameWithType.vb: IConfiguration.Item(String)
  fullName.vb: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  name.vb: Item(String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
    name: Item
    nameWithType: IConfiguration.Item
    fullName: Microsoft.Extensions.Configuration.IConfiguration.Item
  - name: '['
    nameWithType: '['
    fullName: '['
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ']'
    nameWithType: ']'
    fullName: ']'
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
    name: Item
    nameWithType: IConfiguration.Item
    fullName: Microsoft.Extensions.Configuration.IConfiguration.Item
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  parent: Microsoft.Extensions.Configuration.IConfiguration
  isExternal: true
  name: GetSection(String)
  nameWithType: IConfiguration.GetSection(String)
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
    name: GetSection
    nameWithType: IConfiguration.GetSection
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetSection
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
    name: GetSection
    nameWithType: IConfiguration.GetSection
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetSection
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  parent: Microsoft.Extensions.Configuration.IConfiguration
  isExternal: false
  name: GetChildren()
  nameWithType: IConfiguration.GetChildren()
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetChildren()
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
    name: GetChildren
    nameWithType: IConfiguration.GetChildren
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
    name: GetChildren
    nameWithType: IConfiguration.GetChildren
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  parent: Microsoft.Extensions.Configuration.IConfiguration
  isExternal: false
  name: GetReloadToken()
  nameWithType: IConfiguration.GetReloadToken()
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken()
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
    name: GetReloadToken
    nameWithType: IConfiguration.GetReloadToken
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
    name: GetReloadToken
    nameWithType: IConfiguration.GetReloadToken
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  parent: Microsoft.Extensions.Configuration.ConfigurationExtensions
  definition: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  name: GetConnectionString(String)
  nameWithType: ConfigurationExtensions.GetConnectionString(String)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  parent: Microsoft.Extensions.Configuration.ConfigurationExtensions
  definition: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  name: AsEnumerable()
  nameWithType: ConfigurationExtensions.AsEnumerable()
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable()
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration
  commentId: T:Microsoft.Extensions.Configuration.IConfiguration
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Extensions.Configuration.IConfiguration
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  isExternal: true
  name: GetConnectionString(IConfiguration, String)
  nameWithType: ConfigurationExtensions.GetConnectionString(IConfiguration, String)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration, System.String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  isExternal: false
  name: AsEnumerable(IConfiguration)
  nameWithType: ConfigurationExtensions.AsEnumerable(IConfiguration)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfigurationSection.Key*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfigurationSection.Key
  isExternal: false
  name: Key
  nameWithType: IConfigurationSection.Key
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection.Key
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.IConfigurationSection.Path*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfigurationSection.Path
  isExternal: false
  name: Path
  nameWithType: IConfigurationSection.Path
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection.Path
- uid: Microsoft.Extensions.Configuration.IConfigurationSection.Value*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfigurationSection.Value
  isExternal: false
  name: Value
  nameWithType: IConfigurationSection.Value
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection.Value
shouldSkipMarkup: true
