### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention
  id: WebApiOverloadingApplicationModelConvention
  parent: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  children:
  - Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention.Apply(ActionModel)
  langs:
  - csharp
  - vb
  name: WebApiOverloadingApplicationModelConvention
  nameWithType: WebApiOverloadingApplicationModelConvention
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention
  type: Class
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/WebApiOverloadingApplicationModelConvention.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: WebApiOverloadingApplicationModelConvention
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/WebApiOverloadingApplicationModelConvention.cs
    startLine: 9
  assemblies:
  - Microsoft.AspNetCore.Mvc.WebApiCompatShim
  namespace: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  syntax:
    content: 'public class WebApiOverloadingApplicationModelConvention : IActionModelConvention'
    content.vb: >-
      Public Class WebApiOverloadingApplicationModelConvention
          Inherits IActionModelConvention
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention.Apply(ActionModel)
  commentId: M:Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention.Apply(ActionModel)
  id: Apply(ActionModel)
  parent: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention
  langs:
  - csharp
  - vb
  name: Apply(ActionModel)
  nameWithType: WebApiOverloadingApplicationModelConvention.Apply(ActionModel)
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention.Apply(ActionModel)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/WebApiOverloadingApplicationModelConvention.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Apply
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/WebApiOverloadingApplicationModelConvention.cs
    startLine: 11
  assemblies:
  - Microsoft.AspNetCore.Mvc.WebApiCompatShim
  namespace: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  syntax:
    content: public void Apply(ActionModel action)
    parameters:
    - id: action
      type: ActionModel
    content.vb: Public Sub Apply(action As ActionModel)
  overload: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention.Apply*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  commentId: N:Microsoft.AspNetCore.Mvc.WebApiCompatShim
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  nameWithType: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention.Apply*
  commentId: Overload:Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention.Apply
  isExternal: false
  name: Apply
  nameWithType: WebApiOverloadingApplicationModelConvention.Apply
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiOverloadingApplicationModelConvention.Apply
- uid: ActionModel
  isExternal: true
  name: ActionModel
  nameWithType: ActionModel
  fullName: ActionModel
shouldSkipMarkup: true
