### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  id: IniConfigurationSource
  parent: Microsoft.Extensions.Configuration.Ini
  children:
  - Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.Build(IConfigurationBuilder)
  langs:
  - csharp
  - vb
  name: IniConfigurationSource
  nameWithType: IniConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Ini/IniConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: IniConfigurationSource
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Ini/IniConfigurationSource.cs
    startLine: 17
  assemblies:
  - Microsoft.Extensions.Configuration.Ini
  namespace: Microsoft.Extensions.Configuration.Ini
  summary: "\nRepresents an INI file as an <see cref=\"!:IConfigurationSource\"></see>.\nFiles are simple line structures (<a href=\"http://en.wikipedia.org/wiki/INI_file\">INI Files on Wikipedia</a>)\n"
  example: []
  syntax:
    content: 'public class IniConfigurationSource : FileConfigurationSource'
    content.vb: >-
      Public Class IniConfigurationSource
          Inherits FileConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.Build(IConfigurationBuilder)
  commentId: M:Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: IniConfigurationSource.Build(IConfigurationBuilder)
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Ini/IniConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Build
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Ini/IniConfigurationSource.cs
    startLine: 24
  assemblies:
  - Microsoft.Extensions.Configuration.Ini
  namespace: Microsoft.Extensions.Configuration.Ini
  summary: "\nBuilds the <xref href=\"Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider\" data-throw-if-not-resolved=\"false\"></xref> for this source.\n"
  example: []
  syntax:
    content: public override IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see>.
    return:
      type: IConfigurationProvider
      description: An <xref href="Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider" data-throw-if-not-resolved="false"></xref>
    content.vb: Public Overrides Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.Build*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Extensions.Configuration.Ini
  commentId: N:Microsoft.Extensions.Configuration.Ini
  isExternal: false
  name: Microsoft.Extensions.Configuration.Ini
  nameWithType: Microsoft.Extensions.Configuration.Ini
  fullName: Microsoft.Extensions.Configuration.Ini
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
  isExternal: false
  name: IniConfigurationProvider
  nameWithType: IniConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.Build*
  commentId: Overload:Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.Build
  isExternal: false
  name: Build
  nameWithType: IniConfigurationSource.Build
  fullName: Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
shouldSkipMarkup: true
