### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  commentId: T:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  id: EnvironmentTagHelper
  parent: Microsoft.AspNetCore.Mvc.TagHelpers
  children:
  - Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.#ctor(IHostingEnvironment)
  - Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.HostingEnvironment
  - Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Names
  - Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Order
  - Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Process(TagHelperContext,TagHelperOutput)
  langs:
  - csharp
  - vb
  name: EnvironmentTagHelper
  nameWithType: EnvironmentTagHelper
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  type: Class
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: EnvironmentTagHelper
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
    startLine: 14
  assemblies:
  - Microsoft.AspNetCore.Mvc.TagHelpers
  namespace: Microsoft.AspNetCore.Mvc.TagHelpers
  summary: "\n<see cref=\"!:ITagHelper\"></see> implementation targeting &lt;environment> elements that conditionally renders\ncontent based on the current value of <see cref=\"!:IHostingEnvironment.EnvironmentName\"></see>.\n"
  example: []
  syntax:
    content: 'public class EnvironmentTagHelper : TagHelper'
    content.vb: >-
      Public Class EnvironmentTagHelper
          Inherits TagHelper
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.#ctor(IHostingEnvironment)
  commentId: M:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.#ctor(IHostingEnvironment)
  id: '#ctor(IHostingEnvironment)'
  parent: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  langs:
  - csharp
  - vb
  name: EnvironmentTagHelper(IHostingEnvironment)
  nameWithType: EnvironmentTagHelper.EnvironmentTagHelper(IHostingEnvironment)
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.EnvironmentTagHelper(IHostingEnvironment)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: .ctor
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
    startLine: 22
  assemblies:
  - Microsoft.AspNetCore.Mvc.TagHelpers
  namespace: Microsoft.AspNetCore.Mvc.TagHelpers
  summary: "\nCreates a new <xref href=\"Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public EnvironmentTagHelper(IHostingEnvironment hostingEnvironment)
    parameters:
    - id: hostingEnvironment
      type: IHostingEnvironment
      description: The <see cref="!:IHostingEnvironment"></see>.
    content.vb: Public Sub New(hostingEnvironment As IHostingEnvironment)
  overload: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Order
  commentId: P:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Order
  id: Order
  parent: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  langs:
  - csharp
  - vb
  name: Order
  nameWithType: EnvironmentTagHelper.Order
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Order
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Order
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
    startLine: 28
  assemblies:
  - Microsoft.AspNetCore.Mvc.TagHelpers
  namespace: Microsoft.AspNetCore.Mvc.TagHelpers
  example: []
  syntax:
    content: public override int Order { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Overrides ReadOnly Property Order As Integer
  overload: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Order*
  modifiers.csharp:
  - public
  - override
  - get
  modifiers.vb:
  - Public
  - Overrides
  - ReadOnly
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Names
  commentId: P:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Names
  id: Names
  parent: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  langs:
  - csharp
  - vb
  name: Names
  nameWithType: EnvironmentTagHelper.Names
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Names
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Names
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
    startLine: 37
  assemblies:
  - Microsoft.AspNetCore.Mvc.TagHelpers
  namespace: Microsoft.AspNetCore.Mvc.TagHelpers
  summary: "\nA comma separated list of environment names in which the content should be rendered.\n"
  remarks: "\nThe specified environment names are compared case insensitively to the current value of\n<see cref=\"!:IHostingEnvironment.EnvironmentName\"></see>.\n"
  example: []
  syntax:
    content: public string Names { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Names As String
  overload: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Names*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.HostingEnvironment
  commentId: P:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.HostingEnvironment
  id: HostingEnvironment
  parent: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  langs:
  - csharp
  - vb
  name: HostingEnvironment
  nameWithType: EnvironmentTagHelper.HostingEnvironment
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.HostingEnvironment
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: HostingEnvironment
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
    startLine: 39
  assemblies:
  - Microsoft.AspNetCore.Mvc.TagHelpers
  namespace: Microsoft.AspNetCore.Mvc.TagHelpers
  syntax:
    content: protected IHostingEnvironment HostingEnvironment { get; }
    parameters: []
    return:
      type: IHostingEnvironment
    content.vb: Protected ReadOnly Property HostingEnvironment As IHostingEnvironment
  overload: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.HostingEnvironment*
  modifiers.csharp:
  - protected
  - get
  modifiers.vb:
  - Protected
  - ReadOnly
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Process(TagHelperContext,TagHelperOutput)
  commentId: M:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Process(TagHelperContext,TagHelperOutput)
  id: Process(TagHelperContext,TagHelperOutput)
  parent: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  langs:
  - csharp
  - vb
  name: Process(TagHelperContext, TagHelperOutput)
  nameWithType: EnvironmentTagHelper.Process(TagHelperContext, TagHelperOutput)
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Process(TagHelperContext, TagHelperOutput)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Process
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs
    startLine: 42
  assemblies:
  - Microsoft.AspNetCore.Mvc.TagHelpers
  namespace: Microsoft.AspNetCore.Mvc.TagHelpers
  example: []
  syntax:
    content: public override void Process(TagHelperContext context, TagHelperOutput output)
    parameters:
    - id: context
      type: TagHelperContext
    - id: output
      type: TagHelperOutput
    content.vb: Public Overrides Sub Process(context As TagHelperContext, output As TagHelperOutput)
  overload: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Process*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.AspNetCore.Mvc.TagHelpers
  commentId: N:Microsoft.AspNetCore.Mvc.TagHelpers
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.TagHelpers
  nameWithType: Microsoft.AspNetCore.Mvc.TagHelpers
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  commentId: T:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
  isExternal: false
  name: EnvironmentTagHelper
  nameWithType: EnvironmentTagHelper
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.#ctor*
  commentId: Overload:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.#ctor
  isExternal: false
  name: EnvironmentTagHelper
  nameWithType: EnvironmentTagHelper.EnvironmentTagHelper
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.EnvironmentTagHelper
- uid: IHostingEnvironment
  isExternal: true
  name: IHostingEnvironment
  nameWithType: IHostingEnvironment
  fullName: IHostingEnvironment
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Order*
  commentId: Overload:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Order
  isExternal: false
  name: Order
  nameWithType: EnvironmentTagHelper.Order
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Order
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Names*
  commentId: Overload:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Names
  isExternal: false
  name: Names
  nameWithType: EnvironmentTagHelper.Names
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Names
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.HostingEnvironment*
  commentId: Overload:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.HostingEnvironment
  isExternal: false
  name: HostingEnvironment
  nameWithType: EnvironmentTagHelper.HostingEnvironment
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.HostingEnvironment
- uid: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Process*
  commentId: Overload:Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Process
  isExternal: false
  name: Process
  nameWithType: EnvironmentTagHelper.Process
  fullName: Microsoft.AspNetCore.Mvc.TagHelpers.EnvironmentTagHelper.Process
- uid: TagHelperContext
  isExternal: true
  name: TagHelperContext
  nameWithType: TagHelperContext
  fullName: TagHelperContext
- uid: TagHelperOutput
  isExternal: true
  name: TagHelperOutput
  nameWithType: TagHelperOutput
  fullName: TagHelperOutput
shouldSkipMarkup: true
