### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Azure.KeyVault
  commentId: N:Microsoft.Extensions.Configuration.Azure.KeyVault
  id: Microsoft.Extensions.Configuration.Azure.KeyVault
  children:
  - Microsoft.Extensions.Configuration.Azure.KeyVault.DefaultKeyVaultSecretManager
  - Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Azure.KeyVault
  nameWithType: Microsoft.Extensions.Configuration.Azure.KeyVault
  fullName: Microsoft.Extensions.Configuration.Azure.KeyVault
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Azure.KeyVault
references:
- uid: Microsoft.Extensions.Configuration.Azure.KeyVault.DefaultKeyVaultSecretManager
  commentId: T:Microsoft.Extensions.Configuration.Azure.KeyVault.DefaultKeyVaultSecretManager
  isExternal: false
  name: DefaultKeyVaultSecretManager
  nameWithType: DefaultKeyVaultSecretManager
  fullName: Microsoft.Extensions.Configuration.Azure.KeyVault.DefaultKeyVaultSecretManager
- uid: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
  commentId: T:Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
  parent: Microsoft.Extensions.Configuration.Azure.KeyVault
  isExternal: false
  name: IKeyVaultSecretManager
  nameWithType: IKeyVaultSecretManager
  fullName: Microsoft.Extensions.Configuration.Azure.KeyVault.IKeyVaultSecretManager
- uid: Microsoft.Extensions.Configuration.Azure.KeyVault
  commentId: N:Microsoft.Extensions.Configuration.Azure.KeyVault
  isExternal: false
  name: Microsoft.Extensions.Configuration.Azure.KeyVault
  nameWithType: Microsoft.Extensions.Configuration.Azure.KeyVault
  fullName: Microsoft.Extensions.Configuration.Azure.KeyVault
