### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  id: JsonConfigurationSource
  parent: Microsoft.Extensions.Configuration.Json
  children:
  - Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder)
  langs:
  - csharp
  - vb
  name: JsonConfigurationSource
  nameWithType: JsonConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Json/JsonConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: JsonConfigurationSource
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationSource.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.Configuration.Json
  namespace: Microsoft.Extensions.Configuration.Json
  summary: "\nRepresents a JSON file as an <see cref=\"!:IConfigurationSource\"></see>.\n"
  example: []
  syntax:
    content: 'public class JsonConfigurationSource : FileConfigurationSource'
    content.vb: >-
      Public Class JsonConfigurationSource
          Inherits FileConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder)
  commentId: M:Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: JsonConfigurationSource.Build(IConfigurationBuilder)
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Json/JsonConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Build
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationSource.cs
    startLine: 17
  assemblies:
  - Microsoft.Extensions.Configuration.Json
  namespace: Microsoft.Extensions.Configuration.Json
  summary: "\nBuilds the <xref href=\"Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider\" data-throw-if-not-resolved=\"false\"></xref> for this source.\n"
  example: []
  syntax:
    content: public override IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see>.
    return:
      type: IConfigurationProvider
      description: A <xref href="Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider" data-throw-if-not-resolved="false"></xref>
    content.vb: Public Overrides Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Extensions.Configuration.Json
  commentId: N:Microsoft.Extensions.Configuration.Json
  isExternal: false
  name: Microsoft.Extensions.Configuration.Json
  nameWithType: Microsoft.Extensions.Configuration.Json
  fullName: Microsoft.Extensions.Configuration.Json
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  isExternal: false
  name: JsonConfigurationProvider
  nameWithType: JsonConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build*
  commentId: Overload:Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build
  isExternal: false
  name: Build
  nameWithType: JsonConfigurationSource.Build
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
shouldSkipMarkup: true
