### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationSource
  id: FileConfigurationSource
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.FileConfigurationSource.Build(IConfigurationBuilder)
  - Microsoft.Extensions.Configuration.FileConfigurationSource.FileProvider
  - Microsoft.Extensions.Configuration.FileConfigurationSource.Optional
  - Microsoft.Extensions.Configuration.FileConfigurationSource.Path
  - Microsoft.Extensions.Configuration.FileConfigurationSource.ReloadOnChange
  langs:
  - csharp
  - vb
  name: FileConfigurationSource
  nameWithType: FileConfigurationSource
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: FileConfigurationSource
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nRepresents a base class for file based <see cref=\"!:IConfigurationSource\"></see>.\n"
  example: []
  syntax:
    content: 'public abstract class FileConfigurationSource : IConfigurationSource'
    content.vb: >-
      Public MustInherit Class FileConfigurationSource
          Inherits IConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.FileProvider
  commentId: P:Microsoft.Extensions.Configuration.FileConfigurationSource.FileProvider
  id: FileProvider
  parent: Microsoft.Extensions.Configuration.FileConfigurationSource
  langs:
  - csharp
  - vb
  name: FileProvider
  nameWithType: FileConfigurationSource.FileProvider
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.FileProvider
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: FileProvider
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
    startLine: 15
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nUsed to access the contents of the file.\n"
  example: []
  syntax:
    content: public IFileProvider FileProvider { get; set; }
    parameters: []
    return:
      type: IFileProvider
    content.vb: Public Property FileProvider As IFileProvider
  overload: Microsoft.Extensions.Configuration.FileConfigurationSource.FileProvider*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.Path
  commentId: P:Microsoft.Extensions.Configuration.FileConfigurationSource.Path
  id: Path
  parent: Microsoft.Extensions.Configuration.FileConfigurationSource
  langs:
  - csharp
  - vb
  name: Path
  nameWithType: FileConfigurationSource.Path
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.Path
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Path
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
    startLine: 20
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nThe path to the file.\n"
  example: []
  syntax:
    content: public string Path { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Path As String
  overload: Microsoft.Extensions.Configuration.FileConfigurationSource.Path*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.Optional
  commentId: P:Microsoft.Extensions.Configuration.FileConfigurationSource.Optional
  id: Optional
  parent: Microsoft.Extensions.Configuration.FileConfigurationSource
  langs:
  - csharp
  - vb
  name: Optional
  nameWithType: FileConfigurationSource.Optional
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.Optional
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Optional
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
    startLine: 25
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nDetermines if loading the file is optional.\n"
  example: []
  syntax:
    content: public bool Optional { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Optional As Boolean
  overload: Microsoft.Extensions.Configuration.FileConfigurationSource.Optional*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.ReloadOnChange
  commentId: P:Microsoft.Extensions.Configuration.FileConfigurationSource.ReloadOnChange
  id: ReloadOnChange
  parent: Microsoft.Extensions.Configuration.FileConfigurationSource
  langs:
  - csharp
  - vb
  name: ReloadOnChange
  nameWithType: FileConfigurationSource.ReloadOnChange
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.ReloadOnChange
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: ReloadOnChange
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
    startLine: 30
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nDetermines whether the source will be loaded if the underlying file changes.\n"
  example: []
  syntax:
    content: public bool ReloadOnChange { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ReloadOnChange As Boolean
  overload: Microsoft.Extensions.Configuration.FileConfigurationSource.ReloadOnChange*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.Build(IConfigurationBuilder)
  commentId: M:Microsoft.Extensions.Configuration.FileConfigurationSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Microsoft.Extensions.Configuration.FileConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: FileConfigurationSource.Build(IConfigurationBuilder)
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Build
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationSource.cs
    startLine: 37
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nBuilds the <see cref=\"!:IConfigurationProvider\"></see> for this source.\n"
  example: []
  syntax:
    content: public abstract IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see>.
    return:
      type: IConfigurationProvider
      description: A <see cref="!:IConfigurationProvider"></see>
    content.vb: Public MustOverride Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Microsoft.Extensions.Configuration.FileConfigurationSource.Build*
  modifiers.csharp:
  - public
  - abstract
  modifiers.vb:
  - Public
  - MustOverride
references:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.FileProvider*
  commentId: Overload:Microsoft.Extensions.Configuration.FileConfigurationSource.FileProvider
  isExternal: false
  name: FileProvider
  nameWithType: FileConfigurationSource.FileProvider
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.FileProvider
- uid: IFileProvider
  isExternal: true
  name: IFileProvider
  nameWithType: IFileProvider
  fullName: IFileProvider
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.Path*
  commentId: Overload:Microsoft.Extensions.Configuration.FileConfigurationSource.Path
  isExternal: false
  name: Path
  nameWithType: FileConfigurationSource.Path
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.Path
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.Optional*
  commentId: Overload:Microsoft.Extensions.Configuration.FileConfigurationSource.Optional
  isExternal: false
  name: Optional
  nameWithType: FileConfigurationSource.Optional
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.Optional
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.ReloadOnChange*
  commentId: Overload:Microsoft.Extensions.Configuration.FileConfigurationSource.ReloadOnChange
  isExternal: false
  name: ReloadOnChange
  nameWithType: FileConfigurationSource.ReloadOnChange
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.ReloadOnChange
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource.Build*
  commentId: Overload:Microsoft.Extensions.Configuration.FileConfigurationSource.Build
  isExternal: false
  name: Build
  nameWithType: FileConfigurationSource.Build
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
shouldSkipMarkup: true
