### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  id: IParameterModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel)
  langs:
  - csharp
  - vb
  name: IParameterModelConvention
  nameWithType: IParameterModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IParameterModelConvention.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: IParameterModelConvention
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IParameterModelConvention.cs
    startLine: 15
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nAllows customization of the of the <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel\"></see>.\n"
  remarks: "\nTo use this interface, create an <see cref=\"T:System.Attribute\"></see> class which implements the interface and\nplace it on an action method parameter.\n\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention\"></see> customizations run after\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention\"></see> customizations.\n"
  example: []
  syntax:
    content: public interface IParameterModelConvention
    content.vb: Public Interface IParameterModelConvention
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel)
  id: Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention
  langs:
  - csharp
  - vb
  name: Apply(ParameterModel)
  nameWithType: IParameterModelConvention.Apply(ParameterModel)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IParameterModelConvention.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: Apply
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IParameterModelConvention.cs
    startLine: 21
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nCalled to apply the convention to the <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel\"></see>.\n"
  example: []
  syntax:
    content: void Apply(ParameterModel parameter)
    content.vb: Sub Apply(parameter As ParameterModel)
    parameters:
    - id: parameter
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel
      description: The <see cref="T:Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel"></see>.
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ParameterModel
  nameWithType: ParameterModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ParameterModel
