### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  id: EnvironmentVariablesConfigurationProvider
  parent: Microsoft.Extensions.Configuration.EnvironmentVariables
  children:
  - Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor
  - Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor(System.String)
  - Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load
  langs:
  - csharp
  - vb
  name: EnvironmentVariablesConfigurationProvider
  nameWithType: EnvironmentVariablesConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: EnvironmentVariablesConfigurationProvider
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs
    startLine: 13
  assemblies:
  - Microsoft.Extensions.Configuration.EnvironmentVariables
  namespace: Microsoft.Extensions.Configuration.EnvironmentVariables
  summary: "\nAn environment variable based <see cref=\"!:ConfigurationProvider\"></see>.\n"
  example: []
  syntax:
    content: 'public class EnvironmentVariablesConfigurationProvider : ConfigurationProvider'
    content.vb: >-
      Public Class EnvironmentVariablesConfigurationProvider
          Inherits ConfigurationProvider
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor
  commentId: M:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor
  id: '#ctor'
  parent: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  langs:
  - csharp
  - vb
  name: EnvironmentVariablesConfigurationProvider()
  nameWithType: EnvironmentVariablesConfigurationProvider.EnvironmentVariablesConfigurationProvider()
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.EnvironmentVariablesConfigurationProvider()
  type: Constructor
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: .ctor
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs
    startLine: 28
  assemblies:
  - Microsoft.Extensions.Configuration.EnvironmentVariables
  namespace: Microsoft.Extensions.Configuration.EnvironmentVariables
  summary: "\nInitializes a new instance.\n"
  example: []
  syntax:
    content: public EnvironmentVariablesConfigurationProvider()
    content.vb: Public Sub New
  overload: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor(System.String)
  commentId: M:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  langs:
  - csharp
  - vb
  name: EnvironmentVariablesConfigurationProvider(String)
  nameWithType: EnvironmentVariablesConfigurationProvider.EnvironmentVariablesConfigurationProvider(String)
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.EnvironmentVariablesConfigurationProvider(System.String)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: .ctor
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs
    startLine: 35
  assemblies:
  - Microsoft.Extensions.Configuration.EnvironmentVariables
  namespace: Microsoft.Extensions.Configuration.EnvironmentVariables
  summary: "\nInitializes a new instance with the specified prefix.\n"
  example: []
  syntax:
    content: public EnvironmentVariablesConfigurationProvider(string prefix)
    parameters:
    - id: prefix
      type: System.String
      description: A prefix used to filter the environment variables.
    content.vb: Public Sub New(prefix As String)
  overload: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load
  commentId: M:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load
  id: Load
  parent: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: EnvironmentVariablesConfigurationProvider.Load()
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load()
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Load
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs
    startLine: 43
  assemblies:
  - Microsoft.Extensions.Configuration.EnvironmentVariables
  namespace: Microsoft.Extensions.Configuration.EnvironmentVariables
  summary: "\nLoads the environment variables.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables
  commentId: N:Microsoft.Extensions.Configuration.EnvironmentVariables
  isExternal: false
  name: Microsoft.Extensions.Configuration.EnvironmentVariables
  nameWithType: Microsoft.Extensions.Configuration.EnvironmentVariables
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor*
  commentId: Overload:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.#ctor
  isExternal: false
  name: EnvironmentVariablesConfigurationProvider
  nameWithType: EnvironmentVariablesConfigurationProvider.EnvironmentVariablesConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.EnvironmentVariablesConfigurationProvider
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load*
  commentId: Overload:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load
  isExternal: false
  name: Load
  nameWithType: EnvironmentVariablesConfigurationProvider.Load
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load
shouldSkipMarkup: true
