### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  id: IActionModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  langs:
  - csharp
  - vb
  name: IActionModelConvention
  nameWithType: IActionModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IActionModelConvention.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: IActionModelConvention
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IActionModelConvention.cs
    startLine: 16
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nAllows customization of the of the <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel\"></see>.\n"
  remarks: "\nTo use this interface, create an <see cref=\"T:System.Attribute\"></see> class which implements the interface and\nplace it on an action method.\n\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention\"></see> customizations run after\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention\"></see> customications and before\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IParameterModelConvention\"></see> customizations.\n"
  example: []
  syntax:
    content: public interface IActionModelConvention
    content.vb: Public Interface IActionModelConvention
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  id: Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention
  langs:
  - csharp
  - vb
  name: Apply(ActionModel)
  nameWithType: IActionModelConvention.Apply(ActionModel)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IActionModelConvention.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: Apply
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IActionModelConvention.cs
    startLine: 22
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nCalled to apply the convention to the <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel\"></see>.\n"
  example: []
  syntax:
    content: void Apply(ActionModel action)
    content.vb: Sub Apply(action As ActionModel)
    parameters:
    - id: action
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
      description: The <see cref="T:Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel"></see>.
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ActionModel
  nameWithType: ActionModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel
