### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  id: ConfigurationKeyComparer
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare(System.String,System.String)
  - Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Instance
  langs:
  - csharp
  - vb
  name: ConfigurationKeyComparer
  nameWithType: ConfigurationKeyComparer
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/ConfigurationKeyComparer.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: ConfigurationKeyComparer
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/ConfigurationKeyComparer.cs
    startLine: 11
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nIComparer implementation used to order configuration keys.\n"
  example: []
  syntax:
    content: 'public class ConfigurationKeyComparer : IComparer<string>'
    content.vb: >-
      Public Class ConfigurationKeyComparer
          Inherits IComparer(Of String)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Instance
  commentId: P:Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Instance
  id: Instance
  parent: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: ConfigurationKeyComparer.Instance
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Instance
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/ConfigurationKeyComparer.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Instance
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/ConfigurationKeyComparer.cs
    startLine: 18
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nThe default instance.\n"
  example: []
  syntax:
    content: public static ConfigurationKeyComparer Instance { get; }
    parameters: []
    return:
      type: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
    content.vb: Public Shared ReadOnly Property Instance As ConfigurationKeyComparer
  overload: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Instance*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare(System.String,System.String)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare(System.String,System.String)
  id: Compare(System.String,System.String)
  parent: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  langs:
  - csharp
  - vb
  name: Compare(String, String)
  nameWithType: ConfigurationKeyComparer.Compare(String, String)
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare(System.String, System.String)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/ConfigurationKeyComparer.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Compare
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/ConfigurationKeyComparer.cs
    startLine: 26
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nCompares two strings.\n"
  example: []
  syntax:
    content: public int Compare(string x, string y)
    parameters:
    - id: x
      type: System.String
      description: First string.
    - id: y
      type: System.String
      description: Second string.
    return:
      type: System.Int32
      description: ''
    content.vb: Public Function Compare(x As String, y As String) As Integer
  overload: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Instance*
  commentId: Overload:Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Instance
  isExternal: false
  name: Instance
  nameWithType: ConfigurationKeyComparer.Instance
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Instance
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationKeyComparer
  nameWithType: ConfigurationKeyComparer
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare*
  commentId: Overload:Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare
  isExternal: false
  name: Compare
  nameWithType: ConfigurationKeyComparer.Compare
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
shouldSkipMarkup: true
