### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention
  id: WebApiActionConventionsApplicationModelConvention
  parent: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  children:
  - Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention.Apply(ControllerModel)
  langs:
  - csharp
  - vb
  name: WebApiActionConventionsApplicationModelConvention
  nameWithType: WebApiActionConventionsApplicationModelConvention
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention
  type: Class
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/WebApiActionConventionsApplicationModelConvention.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: WebApiActionConventionsApplicationModelConvention
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/WebApiActionConventionsApplicationModelConvention.cs
    startLine: 12
  assemblies:
  - Microsoft.AspNetCore.Mvc.WebApiCompatShim
  namespace: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  syntax:
    content: 'public class WebApiActionConventionsApplicationModelConvention : IControllerModelConvention'
    content.vb: >-
      Public Class WebApiActionConventionsApplicationModelConvention
          Inherits IControllerModelConvention
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention.Apply(ControllerModel)
  commentId: M:Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention.Apply(ControllerModel)
  id: Apply(ControllerModel)
  parent: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention
  langs:
  - csharp
  - vb
  name: Apply(ControllerModel)
  nameWithType: WebApiActionConventionsApplicationModelConvention.Apply(ControllerModel)
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention.Apply(ControllerModel)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/WebApiActionConventionsApplicationModelConvention.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Apply
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/Conventions/WebApiActionConventionsApplicationModelConvention.cs
    startLine: 25
  assemblies:
  - Microsoft.AspNetCore.Mvc.WebApiCompatShim
  namespace: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  syntax:
    content: public void Apply(ControllerModel controller)
    parameters:
    - id: controller
      type: ControllerModel
    content.vb: Public Sub Apply(controller As ControllerModel)
  overload: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention.Apply*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  commentId: N:Microsoft.AspNetCore.Mvc.WebApiCompatShim
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  nameWithType: Microsoft.AspNetCore.Mvc.WebApiCompatShim
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention.Apply*
  commentId: Overload:Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention.Apply
  isExternal: false
  name: Apply
  nameWithType: WebApiActionConventionsApplicationModelConvention.Apply
  fullName: Microsoft.AspNetCore.Mvc.WebApiCompatShim.WebApiActionConventionsApplicationModelConvention.Apply
- uid: ControllerModel
  isExternal: true
  name: ControllerModel
  nameWithType: ControllerModel
  fullName: ControllerModel
shouldSkipMarkup: true
