### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  id: IAuthenticatedEncryptorDescriptor
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  children:
  - Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance
  - Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.ExportToXml
  langs:
  - csharp
  - vb
  name: IAuthenticatedEncryptorDescriptor
  nameWithType: IAuthenticatedEncryptorDescriptor
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
      branch: dev
      repo: https://github.com/aspnet/dataprotection
    id: IAuthenticatedEncryptorDescriptor
    path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
    startLine: 12
  assemblies:
  - Microsoft.AspNetCore.DataProtection
  namespace: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  summary: "\nA self-contained descriptor that wraps all information (including secret key\nmaterial) necessary to create an instance of an <see cref=\"T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor\"></see>.\n"
  example: []
  syntax:
    content: public interface IAuthenticatedEncryptorDescriptor
    content.vb: Public Interface IAuthenticatedEncryptorDescriptor
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance
  id: CreateEncryptorInstance
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  langs:
  - csharp
  - vb
  name: CreateEncryptorInstance()
  nameWithType: IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance()
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.CreateEncryptorInstance()
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
      branch: dev
      repo: https://github.com/aspnet/dataprotection
    id: CreateEncryptorInstance
    path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
    startLine: 23
  assemblies:
  - Microsoft.AspNetCore.DataProtection
  namespace: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  summary: "\nCreates an <see cref=\"T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor\"></see> instance based on the current descriptor.\n"
  remarks: "\nFor a given descriptor, any two instances returned by this method should\nbe considered equivalent, e.g., the payload returned by one's <see cref=\"M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Encrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})\"></see>\nmethod should be consumable by the other's <see cref=\"M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor.Decrypt(System.ArraySegment{System.Byte},System.ArraySegment{System.Byte})\"></see> method.\n"
  example: []
  syntax:
    content: IAuthenticatedEncryptor CreateEncryptorInstance()
    content.vb: Function CreateEncryptorInstance As IAuthenticatedEncryptor
    return:
      type: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
      description: An <see cref="T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor"></see> instance.
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.ExportToXml
  commentId: M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.ExportToXml
  id: ExportToXml
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor
  langs:
  - csharp
  - vb
  name: ExportToXml()
  nameWithType: IAuthenticatedEncryptorDescriptor.ExportToXml()
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptor.ExportToXml()
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
      branch: dev
      repo: https://github.com/aspnet/dataprotection
    id: ExportToXml
    path: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/IAuthenticatedEncryptorDescriptor.cs
    startLine: 38
  assemblies:
  - Microsoft.AspNetCore.DataProtection
  namespace: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  summary: "\nExports the current descriptor to XML.\n"
  remarks: "\nIf an element contains sensitive information (such as key material), the\nelement should be marked via the <see cref=\"M:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlExtensions.MarkAsRequiresEncryption(System.Xml.Linq.XElement)\"></see>\nextension method, and the caller should encrypt the element before persisting\nthe XML to storage.\n"
  example: []
  syntax:
    content: XmlSerializedDescriptorInfo ExportToXml()
    content.vb: Function ExportToXml As XmlSerializedDescriptorInfo
    return:
      type: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo
      description: "\nAn <see cref=\"T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo\"></see> wrapping the <see cref=\"T:System.Xml.Linq.XElement\"></see> which represents the serialized\ncurrent descriptor object. The deserializer type must be assignable to <see cref=\"T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptorDeserializer\"></see>.\n"
references:
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  commentId: N:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  isExternal: false
  name: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  nameWithType: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  isExternal: false
  name: IAuthenticatedEncryptor
  nameWithType: IAuthenticatedEncryptor
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.IAuthenticatedEncryptor
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  commentId: N:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  isExternal: false
  name: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  nameWithType: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption
- uid: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo
  commentId: T:Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo
  parent: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel
  isExternal: false
  name: XmlSerializedDescriptorInfo
  nameWithType: XmlSerializedDescriptorInfo
  fullName: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.XmlSerializedDescriptorInfo
