### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationProvider
  id: FileConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.FileConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.FileConfigurationSource)
  - Microsoft.Extensions.Configuration.FileConfigurationProvider.Load
  - Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(System.IO.Stream)
  - Microsoft.Extensions.Configuration.FileConfigurationProvider.Source
  langs:
  - csharp
  - vb
  name: FileConfigurationProvider
  nameWithType: FileConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: FileConfigurationProvider
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
    startLine: 13
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nBase class for file based <see cref=\"!:ConfigurationProvider\"></see>.\n"
  example: []
  syntax:
    content: 'public abstract class FileConfigurationProvider : ConfigurationProvider'
    content.vb: >-
      Public MustInherit Class FileConfigurationProvider
          Inherits ConfigurationProvider
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.FileConfigurationSource)
  commentId: M:Microsoft.Extensions.Configuration.FileConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.FileConfigurationSource)
  id: '#ctor(Microsoft.Extensions.Configuration.FileConfigurationSource)'
  parent: Microsoft.Extensions.Configuration.FileConfigurationProvider
  langs:
  - csharp
  - vb
  name: FileConfigurationProvider(FileConfigurationSource)
  nameWithType: FileConfigurationProvider.FileConfigurationProvider(FileConfigurationSource)
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider.FileConfigurationProvider(Microsoft.Extensions.Configuration.FileConfigurationSource)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: .ctor
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
    startLine: 19
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nInitializes a new instance with the specified source.\n"
  example: []
  syntax:
    content: public FileConfigurationProvider(FileConfigurationSource source)
    parameters:
    - id: source
      type: Microsoft.Extensions.Configuration.FileConfigurationSource
      description: The source settings.
    content.vb: Public Sub New(source As FileConfigurationSource)
  overload: Microsoft.Extensions.Configuration.FileConfigurationProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider.Source
  commentId: P:Microsoft.Extensions.Configuration.FileConfigurationProvider.Source
  id: Source
  parent: Microsoft.Extensions.Configuration.FileConfigurationProvider
  langs:
  - csharp
  - vb
  name: Source
  nameWithType: FileConfigurationProvider.Source
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider.Source
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Source
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
    startLine: 38
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nThe source settings for this provider.\n"
  example: []
  syntax:
    content: public FileConfigurationSource Source { get; }
    parameters: []
    return:
      type: Microsoft.Extensions.Configuration.FileConfigurationSource
    content.vb: Public ReadOnly Property Source As FileConfigurationSource
  overload: Microsoft.Extensions.Configuration.FileConfigurationProvider.Source*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider.Load
  commentId: M:Microsoft.Extensions.Configuration.FileConfigurationProvider.Load
  id: Load
  parent: Microsoft.Extensions.Configuration.FileConfigurationProvider
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: FileConfigurationProvider.Load()
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Load
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
    startLine: 70
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nLoads the contents of the file at <xref href=\"System.IO.Path\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Microsoft.Extensions.Configuration.FileConfigurationProvider.Load*
  exceptions:
  - type: System.IO.FileNotFoundException
    commentId: T:System.IO.FileNotFoundException
    description: >-
      If Optional is <code>false</code> on the source and a

      file does not exist at specified Path.
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(System.IO.Stream)
  commentId: M:Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(System.IO.Stream)
  id: Load(System.IO.Stream)
  parent: Microsoft.Extensions.Configuration.FileConfigurationProvider
  langs:
  - csharp
  - vb
  name: Load(Stream)
  nameWithType: FileConfigurationProvider.Load(Stream)
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(System.IO.Stream)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Load
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs
    startLine: 79
  assemblies:
  - Microsoft.Extensions.Configuration.FileExtensions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nLoads this provider's data from a stream.\n"
  example: []
  syntax:
    content: public abstract void Load(Stream stream)
    parameters:
    - id: stream
      type: System.IO.Stream
      description: The stream to read.
    content.vb: Public MustOverride Sub Load(stream As Stream)
  overload: Microsoft.Extensions.Configuration.FileConfigurationProvider.Load*
  modifiers.csharp:
  - public
  - abstract
  modifiers.vb:
  - Public
  - MustOverride
references:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider.#ctor*
  commentId: Overload:Microsoft.Extensions.Configuration.FileConfigurationProvider.#ctor
  isExternal: false
  name: FileConfigurationProvider
  nameWithType: FileConfigurationProvider.FileConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider.FileConfigurationProvider
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationSource
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: FileConfigurationSource
  nameWithType: FileConfigurationSource
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider.Source*
  commentId: Overload:Microsoft.Extensions.Configuration.FileConfigurationProvider.Source
  isExternal: false
  name: Source
  nameWithType: FileConfigurationProvider.Source
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider.Source
- uid: System.IO.Path
  commentId: T:System.IO.Path
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider.Load*
  commentId: Overload:Microsoft.Extensions.Configuration.FileConfigurationProvider.Load
  isExternal: false
  name: Load
  nameWithType: FileConfigurationProvider.Load
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider.Load
- uid: System.IO.FileNotFoundException
  commentId: T:System.IO.FileNotFoundException
- uid: System.IO.Stream
  commentId: T:System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.IO
  commentId: N:System.IO
  isExternal: false
  name: System.IO
  nameWithType: System.IO
  fullName: System.IO
shouldSkipMarkup: true
