### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.IConfigurationRoot
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationRoot
  id: IConfigurationRoot
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.IConfigurationRoot.Reload
  langs:
  - csharp
  - vb
  name: IConfigurationRoot
  nameWithType: IConfigurationRoot
  fullName: Microsoft.Extensions.Configuration.IConfigurationRoot
  type: Interface
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationRoot.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: IConfigurationRoot
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationRoot.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nRepresents the root of an <xref href=\"Microsoft.Extensions.Configuration.IConfiguration\" data-throw-if-not-resolved=\"false\"></xref> hierarchy.\n"
  example: []
  syntax:
    content: 'public interface IConfigurationRoot : IConfiguration'
    content.vb: >-
      Public Interface IConfigurationRoot
          Inherits IConfiguration
  inheritedMembers:
  - Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  - Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  - Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  - Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  extensionMethods:
  - Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  - Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Extensions.Configuration.IConfigurationRoot.Reload
  commentId: M:Microsoft.Extensions.Configuration.IConfigurationRoot.Reload
  id: Reload
  parent: Microsoft.Extensions.Configuration.IConfigurationRoot
  langs:
  - csharp
  - vb
  name: Reload()
  nameWithType: IConfigurationRoot.Reload()
  fullName: Microsoft.Extensions.Configuration.IConfigurationRoot.Reload()
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationRoot.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Reload
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationRoot.cs
    startLine: 15
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nForce the configuration values to be reloaded from the underlying <xref href=\"Microsoft.Extensions.Configuration.IConfigurationProvider\" data-throw-if-not-resolved=\"false\"></xref>s.\n"
  example: []
  syntax:
    content: void Reload()
    content.vb: Sub Reload
  overload: Microsoft.Extensions.Configuration.IConfigurationRoot.Reload*
references:
- uid: Microsoft.Extensions.Configuration.IConfiguration
  commentId: T:Microsoft.Extensions.Configuration.IConfiguration
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Extensions.Configuration.IConfiguration
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  commentId: P:Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  parent: Microsoft.Extensions.Configuration.IConfiguration
  isExternal: true
  name: Item[String]
  nameWithType: IConfiguration.Item[String]
  fullName: Microsoft.Extensions.Configuration.IConfiguration.Item[System.String]
  nameWithType.vb: IConfiguration.Item(String)
  fullName.vb: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
  name.vb: Item(String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
    name: Item
    nameWithType: IConfiguration.Item
    fullName: Microsoft.Extensions.Configuration.IConfiguration.Item
  - name: '['
    nameWithType: '['
    fullName: '['
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ']'
    nameWithType: ']'
    fullName: ']'
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.Item(System.String)
    name: Item
    nameWithType: IConfiguration.Item
    fullName: Microsoft.Extensions.Configuration.IConfiguration.Item
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  parent: Microsoft.Extensions.Configuration.IConfiguration
  isExternal: true
  name: GetSection(String)
  nameWithType: IConfiguration.GetSection(String)
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
    name: GetSection
    nameWithType: IConfiguration.GetSection
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetSection
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetSection(System.String)
    name: GetSection
    nameWithType: IConfiguration.GetSection
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetSection
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  parent: Microsoft.Extensions.Configuration.IConfiguration
  isExternal: false
  name: GetChildren()
  nameWithType: IConfiguration.GetChildren()
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetChildren()
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
    name: GetChildren
    nameWithType: IConfiguration.GetChildren
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
    name: GetChildren
    nameWithType: IConfiguration.GetChildren
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetChildren
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  commentId: M:Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  parent: Microsoft.Extensions.Configuration.IConfiguration
  isExternal: false
  name: GetReloadToken()
  nameWithType: IConfiguration.GetReloadToken()
  fullName: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken()
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
    name: GetReloadToken
    nameWithType: IConfiguration.GetReloadToken
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
    name: GetReloadToken
    nameWithType: IConfiguration.GetReloadToken
    fullName: Microsoft.Extensions.Configuration.IConfiguration.GetReloadToken
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  parent: Microsoft.Extensions.Configuration.ConfigurationExtensions
  definition: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  name: GetConnectionString(String)
  nameWithType: ConfigurationExtensions.GetConnectionString(String)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfiguration.Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  parent: Microsoft.Extensions.Configuration.ConfigurationExtensions
  definition: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  name: AsEnumerable()
  nameWithType: ConfigurationExtensions.AsEnumerable()
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable()
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  isExternal: true
  name: GetConnectionString(IConfiguration, String)
  nameWithType: ConfigurationExtensions.GetConnectionString(IConfiguration, String)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration, System.String)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString(Microsoft.Extensions.Configuration.IConfiguration,System.String)
    name: GetConnectionString
    nameWithType: ConfigurationExtensions.GetConnectionString
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.GetConnectionString
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  isExternal: false
  name: AsEnumerable(IConfiguration)
  nameWithType: ConfigurationExtensions.AsEnumerable(IConfiguration)
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(Microsoft.Extensions.Configuration.IConfiguration)
    name: AsEnumerable
    nameWithType: ConfigurationExtensions.AsEnumerable
    fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable
  - name: (
    nameWithType: (
    fullName: (
  - uid: Microsoft.Extensions.Configuration.IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: Microsoft.Extensions.Configuration.IConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.IConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.IConfigurationProvider
- uid: Microsoft.Extensions.Configuration.IConfigurationRoot.Reload*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfigurationRoot.Reload
  isExternal: false
  name: Reload
  nameWithType: IConfigurationRoot.Reload
  fullName: Microsoft.Extensions.Configuration.IConfigurationRoot.Reload
shouldSkipMarkup: true
