### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  id: XmlConfigurationSource
  parent: Microsoft.Extensions.Configuration.Xml
  children:
  - Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.Build(IConfigurationBuilder)
  langs:
  - csharp
  - vb
  name: XmlConfigurationSource
  nameWithType: XmlConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: XmlConfigurationSource
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationSource.cs
    startLine: 8
  assemblies:
  - Microsoft.Extensions.Configuration.Xml
  namespace: Microsoft.Extensions.Configuration.Xml
  summary: "\nAn XML file based <see cref=\"!:FileConfigurationSource\"></see>.\n"
  example: []
  syntax:
    content: 'public class XmlConfigurationSource : FileConfigurationSource'
    content.vb: >-
      Public Class XmlConfigurationSource
          Inherits FileConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.Build(IConfigurationBuilder)
  commentId: M:Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: XmlConfigurationSource.Build(IConfigurationBuilder)
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Build
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationSource.cs
    startLine: 15
  assemblies:
  - Microsoft.Extensions.Configuration.Xml
  namespace: Microsoft.Extensions.Configuration.Xml
  summary: "\nBuilds the <xref href=\"Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider\" data-throw-if-not-resolved=\"false\"></xref> for this source.\n"
  example: []
  syntax:
    content: public override IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see>.
    return:
      type: IConfigurationProvider
      description: A <xref href="Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider" data-throw-if-not-resolved="false"></xref>
    content.vb: Public Overrides Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.Build*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Extensions.Configuration.Xml
  commentId: N:Microsoft.Extensions.Configuration.Xml
  isExternal: false
  name: Microsoft.Extensions.Configuration.Xml
  nameWithType: Microsoft.Extensions.Configuration.Xml
  fullName: Microsoft.Extensions.Configuration.Xml
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  isExternal: false
  name: XmlConfigurationProvider
  nameWithType: XmlConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.Build*
  commentId: Overload:Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.Build
  isExternal: false
  name: Build
  nameWithType: XmlConfigurationSource.Build
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
shouldSkipMarkup: true
