### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform
  commentId: T:Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform
  id: WebConfigTransform
  parent: Microsoft.AspNetCore.Server.IISIntegration.Tools
  children:
  - Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform.Transform(XDocument,System.String,System.Boolean,System.Boolean)
  langs:
  - csharp
  - vb
  name: WebConfigTransform
  nameWithType: WebConfigTransform
  fullName: Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform
  type: Class
  source:
    remote:
      path: src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
      branch: master
      repo: https://github.com/aspnet/IISIntegration.git
    id: WebConfigTransform
    path: ../aspnet/IISIntegration/src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
    startLine: 10
  assemblies:
  - Microsoft.AspNetCore.Server.IISIntegration.Tools
  namespace: Microsoft.AspNetCore.Server.IISIntegration.Tools
  syntax:
    content: 'public static class WebConfigTransform : object'
    content.vb: >-
      Public Module WebConfigTransform
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform.Transform(XDocument,System.String,System.Boolean,System.Boolean)
  commentId: M:Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform.Transform(XDocument,System.String,System.Boolean,System.Boolean)
  id: Transform(XDocument,System.String,System.Boolean,System.Boolean)
  parent: Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform
  langs:
  - csharp
  - vb
  name: Transform(XDocument, String, Boolean, Boolean)
  nameWithType: WebConfigTransform.Transform(XDocument, String, Boolean, Boolean)
  fullName: Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform.Transform(XDocument, System.String, System.Boolean, System.Boolean)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
      branch: master
      repo: https://github.com/aspnet/IISIntegration.git
    id: Transform
    path: ../aspnet/IISIntegration/src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
    startLine: 12
  assemblies:
  - Microsoft.AspNetCore.Server.IISIntegration.Tools
  namespace: Microsoft.AspNetCore.Server.IISIntegration.Tools
  syntax:
    content: public static XDocument Transform(XDocument webConfig, string appName, bool configureForAzure, bool isPortable)
    parameters:
    - id: webConfig
      type: XDocument
    - id: appName
      type: System.String
    - id: configureForAzure
      type: System.Boolean
    - id: isPortable
      type: System.Boolean
    return:
      type: XDocument
    content.vb: Public Shared Function Transform(webConfig As XDocument, appName As String, configureForAzure As Boolean, isPortable As Boolean) As XDocument
  overload: Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform.Transform*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Microsoft.AspNetCore.Server.IISIntegration.Tools
  commentId: N:Microsoft.AspNetCore.Server.IISIntegration.Tools
  isExternal: false
  name: Microsoft.AspNetCore.Server.IISIntegration.Tools
  nameWithType: Microsoft.AspNetCore.Server.IISIntegration.Tools
  fullName: Microsoft.AspNetCore.Server.IISIntegration.Tools
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform.Transform*
  commentId: Overload:Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform.Transform
  isExternal: false
  name: Transform
  nameWithType: WebConfigTransform.Transform
  fullName: Microsoft.AspNetCore.Server.IISIntegration.Tools.WebConfigTransform.Transform
- uid: XDocument
  isExternal: true
  name: XDocument
  nameWithType: XDocument
  fullName: XDocument
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
shouldSkipMarkup: true
