### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  id: JsonConfigurationProvider
  parent: Microsoft.Extensions.Configuration.Json
  children:
  - Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Json.JsonConfigurationSource)
  - Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(System.IO.Stream)
  langs:
  - csharp
  - vb
  name: JsonConfigurationProvider
  nameWithType: JsonConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Json/JsonConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: JsonConfigurationProvider
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationProvider.cs
    startLine: 14
  assemblies:
  - Microsoft.Extensions.Configuration.Json
  namespace: Microsoft.Extensions.Configuration.Json
  summary: "\nA JSON file based <see cref=\"!:FileConfigurationProvider\"></see>.\n"
  example: []
  syntax:
    content: 'public class JsonConfigurationProvider : FileConfigurationProvider'
    content.vb: >-
      Public Class JsonConfigurationProvider
          Inherits FileConfigurationProvider
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Json.JsonConfigurationSource)
  commentId: M:Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Json.JsonConfigurationSource)
  id: '#ctor(Microsoft.Extensions.Configuration.Json.JsonConfigurationSource)'
  parent: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  langs:
  - csharp
  - vb
  name: JsonConfigurationProvider(JsonConfigurationSource)
  nameWithType: JsonConfigurationProvider.JsonConfigurationProvider(JsonConfigurationSource)
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.JsonConfigurationProvider(Microsoft.Extensions.Configuration.Json.JsonConfigurationSource)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Json/JsonConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: .ctor
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationProvider.cs
    startLine: 20
  assemblies:
  - Microsoft.Extensions.Configuration.Json
  namespace: Microsoft.Extensions.Configuration.Json
  summary: "\nInitializes a new instance with the specified source.\n"
  example: []
  syntax:
    content: public JsonConfigurationProvider(JsonConfigurationSource source)
    parameters:
    - id: source
      type: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
      description: The source settings.
    content.vb: Public Sub New(source As JsonConfigurationSource)
  overload: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(System.IO.Stream)
  commentId: M:Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(System.IO.Stream)
  id: Load(System.IO.Stream)
  parent: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  langs:
  - csharp
  - vb
  name: Load(Stream)
  nameWithType: JsonConfigurationProvider.Load(Stream)
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(System.IO.Stream)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Json/JsonConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Load
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationProvider.cs
    startLine: 26
  assemblies:
  - Microsoft.Extensions.Configuration.Json
  namespace: Microsoft.Extensions.Configuration.Json
  summary: "\nLoads the JSON data from a stream.\n"
  example: []
  syntax:
    content: public override void Load(Stream stream)
    parameters:
    - id: stream
      type: System.IO.Stream
      description: The stream to read.
    content.vb: Public Overrides Sub Load(stream As Stream)
  overload: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Extensions.Configuration.Json
  commentId: N:Microsoft.Extensions.Configuration.Json
  isExternal: false
  name: Microsoft.Extensions.Configuration.Json
  nameWithType: Microsoft.Extensions.Configuration.Json
  fullName: Microsoft.Extensions.Configuration.Json
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.#ctor*
  commentId: Overload:Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.#ctor
  isExternal: false
  name: JsonConfigurationProvider
  nameWithType: JsonConfigurationProvider.JsonConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.JsonConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  parent: Microsoft.Extensions.Configuration.Json
  isExternal: false
  name: JsonConfigurationSource
  nameWithType: JsonConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load*
  commentId: Overload:Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load
  isExternal: false
  name: Load
  nameWithType: JsonConfigurationProvider.Load
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load
- uid: System.IO.Stream
  commentId: T:System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.IO
  commentId: N:System.IO
  isExternal: false
  name: System.IO
  nameWithType: System.IO
  fullName: System.IO
shouldSkipMarkup: true
