### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1
  commentId: T:Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1
  id: ConfigureFromConfigurationOptions`1
  parent: Microsoft.Extensions.Options
  children:
  - Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1.#ctor(IConfiguration)
  langs:
  - csharp
  - vb
  name: ConfigureFromConfigurationOptions<TOptions>
  nameWithType: ConfigureFromConfigurationOptions<TOptions>
  fullName: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions<TOptions>
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Options.ConfigurationExtensions/ConfigureFromConfigurationOptions.cs
      branch: master
      repo: https://github.com/aspnet/Options.git
    id: ConfigureFromConfigurationOptions
    path: ../aspnet/Options/src/Microsoft.Extensions.Options.ConfigurationExtensions/ConfigureFromConfigurationOptions.cs
    startLine: 12
  assemblies:
  - Microsoft.Extensions.Options.ConfigurationExtensions
  namespace: Microsoft.Extensions.Options
  summary: "\nConfigures an option instance by using ConfigurationBinder.Bind against an IConfiguration.\n"
  example: []
  syntax:
    content: 'public class ConfigureFromConfigurationOptions<TOptions> : ConfigureOptions<TOptions> where TOptions : class'
    typeParameters:
    - id: TOptions
      description: The type of options to bind.
    content.vb: >-
      Public Class ConfigureFromConfigurationOptions(Of TOptions As Class)
          Inherits ConfigureOptions(Of TOptions)
  inheritance:
  - System.Object
  nameWithType.vb: ConfigureFromConfigurationOptions(Of TOptions)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions(Of TOptions)
  name.vb: ConfigureFromConfigurationOptions(Of TOptions)
- uid: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1.#ctor(IConfiguration)
  commentId: M:Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1.#ctor(IConfiguration)
  id: '#ctor(IConfiguration)'
  parent: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1
  langs:
  - csharp
  - vb
  name: ConfigureFromConfigurationOptions(IConfiguration)
  nameWithType: ConfigureFromConfigurationOptions<TOptions>.ConfigureFromConfigurationOptions(IConfiguration)
  fullName: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions<TOptions>.ConfigureFromConfigurationOptions(IConfiguration)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.Extensions.Options.ConfigurationExtensions/ConfigureFromConfigurationOptions.cs
      branch: master
      repo: https://github.com/aspnet/Options.git
    id: .ctor
    path: ../aspnet/Options/src/Microsoft.Extensions.Options.ConfigurationExtensions/ConfigureFromConfigurationOptions.cs
    startLine: 19
  assemblies:
  - Microsoft.Extensions.Options.ConfigurationExtensions
  namespace: Microsoft.Extensions.Options
  summary: "\nConstructor that takes the IConfiguration instance to bind against.\n"
  example: []
  syntax:
    content: public ConfigureFromConfigurationOptions(IConfiguration config)
    parameters:
    - id: config
      type: IConfiguration
      description: The IConfiguration instance.
    content.vb: Public Sub New(config As IConfiguration)
  overload: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1.#ctor*
  nameWithType.vb: ConfigureFromConfigurationOptions(Of TOptions).ConfigureFromConfigurationOptions(IConfiguration)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions(Of TOptions).ConfigureFromConfigurationOptions(IConfiguration)
references:
- uid: Microsoft.Extensions.Options
  commentId: N:Microsoft.Extensions.Options
  isExternal: false
  name: Microsoft.Extensions.Options
  nameWithType: Microsoft.Extensions.Options
  fullName: Microsoft.Extensions.Options
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1.#ctor*
  commentId: Overload:Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1.#ctor
  isExternal: false
  name: ConfigureFromConfigurationOptions
  nameWithType: ConfigureFromConfigurationOptions<TOptions>.ConfigureFromConfigurationOptions
  fullName: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions<TOptions>.ConfigureFromConfigurationOptions
  nameWithType.vb: ConfigureFromConfigurationOptions(Of TOptions).ConfigureFromConfigurationOptions
  fullName.vb: Microsoft.Extensions.Options.ConfigureFromConfigurationOptions(Of TOptions).ConfigureFromConfigurationOptions
- uid: IConfiguration
  isExternal: true
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: IConfiguration
shouldSkipMarkup: true
