### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  commentId: T:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  id: HostingEnvironment
  parent: Microsoft.AspNetCore.Hosting.Internal
  children:
  - Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ApplicationName
  - Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootFileProvider
  - Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootPath
  - Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.EnvironmentName
  - Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootFileProvider
  - Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootPath
  langs:
  - csharp
  - vb
  name: HostingEnvironment
  nameWithType: HostingEnvironment
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  type: Class
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: HostingEnvironment
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
    startLine: 7
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: 'public class HostingEnvironment : IHostingEnvironment'
    content.vb: >-
      Public Class HostingEnvironment
          Inherits IHostingEnvironment
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.EnvironmentName
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.EnvironmentName
  id: EnvironmentName
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  langs:
  - csharp
  - vb
  name: EnvironmentName
  nameWithType: HostingEnvironment.EnvironmentName
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.EnvironmentName
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: EnvironmentName
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
    startLine: 9
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public string EnvironmentName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property EnvironmentName As String
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.EnvironmentName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ApplicationName
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ApplicationName
  id: ApplicationName
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  langs:
  - csharp
  - vb
  name: ApplicationName
  nameWithType: HostingEnvironment.ApplicationName
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ApplicationName
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: ApplicationName
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
    startLine: 11
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public string ApplicationName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ApplicationName As String
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ApplicationName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootPath
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootPath
  id: WebRootPath
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  langs:
  - csharp
  - vb
  name: WebRootPath
  nameWithType: HostingEnvironment.WebRootPath
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootPath
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: WebRootPath
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
    startLine: 13
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public string WebRootPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WebRootPath As String
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootPath*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootFileProvider
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootFileProvider
  id: WebRootFileProvider
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  langs:
  - csharp
  - vb
  name: WebRootFileProvider
  nameWithType: HostingEnvironment.WebRootFileProvider
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootFileProvider
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: WebRootFileProvider
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
    startLine: 15
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public IFileProvider WebRootFileProvider { get; set; }
    parameters: []
    return:
      type: IFileProvider
    content.vb: Public Property WebRootFileProvider As IFileProvider
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootFileProvider*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootPath
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootPath
  id: ContentRootPath
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  langs:
  - csharp
  - vb
  name: ContentRootPath
  nameWithType: HostingEnvironment.ContentRootPath
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootPath
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: ContentRootPath
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
    startLine: 17
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public string ContentRootPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ContentRootPath As String
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootPath*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootFileProvider
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootFileProvider
  id: ContentRootFileProvider
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment
  langs:
  - csharp
  - vb
  name: ContentRootFileProvider
  nameWithType: HostingEnvironment.ContentRootFileProvider
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootFileProvider
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: ContentRootFileProvider
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs
    startLine: 19
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public IFileProvider ContentRootFileProvider { get; set; }
    parameters: []
    return:
      type: IFileProvider
    content.vb: Public Property ContentRootFileProvider As IFileProvider
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootFileProvider*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.AspNetCore.Hosting.Internal
  commentId: N:Microsoft.AspNetCore.Hosting.Internal
  isExternal: false
  name: Microsoft.AspNetCore.Hosting.Internal
  nameWithType: Microsoft.AspNetCore.Hosting.Internal
  fullName: Microsoft.AspNetCore.Hosting.Internal
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.EnvironmentName*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.EnvironmentName
  isExternal: false
  name: EnvironmentName
  nameWithType: HostingEnvironment.EnvironmentName
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.EnvironmentName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ApplicationName*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ApplicationName
  isExternal: false
  name: ApplicationName
  nameWithType: HostingEnvironment.ApplicationName
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ApplicationName
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootPath*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootPath
  isExternal: false
  name: WebRootPath
  nameWithType: HostingEnvironment.WebRootPath
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootPath
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootFileProvider*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootFileProvider
  isExternal: false
  name: WebRootFileProvider
  nameWithType: HostingEnvironment.WebRootFileProvider
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.WebRootFileProvider
- uid: IFileProvider
  isExternal: true
  name: IFileProvider
  nameWithType: IFileProvider
  fullName: IFileProvider
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootPath*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootPath
  isExternal: false
  name: ContentRootPath
  nameWithType: HostingEnvironment.ContentRootPath
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootPath
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootFileProvider*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootFileProvider
  isExternal: false
  name: ContentRootFileProvider
  nameWithType: HostingEnvironment.ContentRootFileProvider
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment.ContentRootFileProvider
shouldSkipMarkup: true
