### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
  id: IApplicationFeatureProvider
  parent: Microsoft.AspNetCore.Mvc.ApplicationParts
  children: []
  langs:
  - csharp
  - vb
  name: IApplicationFeatureProvider
  nameWithType: IApplicationFeatureProvider
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/IApplicationFeatureProvider.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: IApplicationFeatureProvider
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/IApplicationFeatureProvider.cs
    startLine: 9
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationParts
  summary: "\nMarker interface for <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationParts.IApplicationFeatureProvider\"></see>\nimplementations.\n"
  example: []
  syntax:
    content: public interface IApplicationFeatureProvider
    content.vb: Public Interface IApplicationFeatureProvider
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationParts
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationParts
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationParts
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationParts
  fullName: Microsoft.AspNetCore.Mvc.ApplicationParts
