### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  id: IControllerModelConvention
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  children:
  - Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  langs:
  - csharp
  - vb
  name: IControllerModelConvention
  nameWithType: IControllerModelConvention
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IControllerModelConvention.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: IControllerModelConvention
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IControllerModelConvention.cs
    startLine: 16
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nAllows customization of the of the <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel\"></see>.\n"
  remarks: "\nTo use this interface, create an <see cref=\"T:System.Attribute\"></see> class which implements the interface and\nplace it on a controller class.\n\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention\"></see> customizations run after\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelConvention\"></see> customizations and before\n<see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.IActionModelConvention\"></see> customizations.\n"
  example: []
  syntax:
    content: public interface IControllerModelConvention
    content.vb: Public Interface IControllerModelConvention
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  commentId: M:Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  id: Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention
  langs:
  - csharp
  - vb
  name: Apply(ControllerModel)
  nameWithType: IControllerModelConvention.Apply(ControllerModel)
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.IControllerModelConvention.Apply(Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IControllerModelConvention.cs
      branch: dev
      repo: https://github.com/aspnet/mvc
    id: Apply
    path: src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/IControllerModelConvention.cs
    startLine: 22
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Mvc.ApplicationModels
  summary: "\nCalled to apply the convention to the <see cref=\"T:Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel\"></see>.\n"
  example: []
  syntax:
    content: void Apply(ControllerModel controller)
    content.vb: Sub Apply(controller As ControllerModel)
    parameters:
    - id: controller
      type: Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
      description: The <see cref="T:Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel"></see>.
references:
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels
  commentId: N:Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.ApplicationModels
  nameWithType: Microsoft.AspNetCore.Mvc.ApplicationModels
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels
- uid: Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
  commentId: T:Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
  parent: Microsoft.AspNetCore.Mvc.ApplicationModels
  isExternal: false
  name: ControllerModel
  nameWithType: ControllerModel
  fullName: Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerModel
