### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.IConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationSource
  id: IConfigurationSource
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.IConfigurationSource.Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
  langs:
  - csharp
  - vb
  name: IConfigurationSource
  nameWithType: IConfigurationSource
  fullName: Microsoft.Extensions.Configuration.IConfigurationSource
  type: Interface
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
      commit: 290b4989d409db0f3d73db93b2c1d2cd81a157a5
    id: IConfigurationSource
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSource.cs
    startLine: 10
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nRepresents a source of configuration key/values for an application.\n"
  example: []
  syntax:
    content: public interface IConfigurationSource
    content.vb: Public Interface IConfigurationSource
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Extensions.Configuration.IConfigurationSource.Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
  commentId: M:Microsoft.Extensions.Configuration.IConfigurationSource.Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
  id: Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
  parent: Microsoft.Extensions.Configuration.IConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: IConfigurationSource.Build(IConfigurationBuilder)
  fullName: Microsoft.Extensions.Configuration.IConfigurationSource.Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
      commit: 290b4989d409db0f3d73db93b2c1d2cd81a157a5
    id: Build
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationSource.cs
    startLine: 17
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
  namespace: Microsoft.Extensions.Configuration
  summary: "\nBuilds the <xref href=\"Microsoft.Extensions.Configuration.IConfigurationProvider\" data-throw-if-not-resolved=\"false\"></xref> for this source.\n"
  example: []
  syntax:
    content: IConfigurationProvider Build(IConfigurationBuilder builder)
    content.vb: Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
    parameters:
    - id: builder
      type: Microsoft.Extensions.Configuration.IConfigurationBuilder
      description: The <xref href="Microsoft.Extensions.Configuration.IConfigurationBuilder" data-throw-if-not-resolved="false"></xref>.
    return:
      type: Microsoft.Extensions.Configuration.IConfigurationProvider
      description: An <xref href="Microsoft.Extensions.Configuration.IConfigurationProvider" data-throw-if-not-resolved="false"></xref>
  overload: Microsoft.Extensions.Configuration.IConfigurationSource.Build*
references:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: Microsoft.Extensions.Configuration.IConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.IConfigurationProvider
- uid: Microsoft.Extensions.Configuration.IConfigurationBuilder
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationBuilder
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: Microsoft.Extensions.Configuration.IConfigurationBuilder
- uid: Microsoft.Extensions.Configuration.IConfigurationSource.Build*
  commentId: Overload:Microsoft.Extensions.Configuration.IConfigurationSource.Build
  isExternal: false
  name: Build
  nameWithType: IConfigurationSource.Build
  fullName: Microsoft.Extensions.Configuration.IConfigurationSource.Build
shouldSkipMarkup: true
