### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  id: XmlConfigurationProvider
  parent: Microsoft.Extensions.Configuration.Xml
  children:
  - Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource)
  - Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load(System.IO.Stream)
  langs:
  - csharp
  - vb
  name: XmlConfigurationProvider
  nameWithType: XmlConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: XmlConfigurationProvider
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationProvider.cs
    startLine: 14
  assemblies:
  - Microsoft.Extensions.Configuration.Xml
  namespace: Microsoft.Extensions.Configuration.Xml
  summary: "\nRepresents an XML file as an <see cref=\"!:IConfigurationSource\"></see>.\n"
  example: []
  syntax:
    content: 'public class XmlConfigurationProvider : FileConfigurationProvider'
    content.vb: >-
      Public Class XmlConfigurationProvider
          Inherits FileConfigurationProvider
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource)
  commentId: M:Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.#ctor(Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource)
  id: '#ctor(Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource)'
  parent: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  langs:
  - csharp
  - vb
  name: XmlConfigurationProvider(XmlConfigurationSource)
  nameWithType: XmlConfigurationProvider.XmlConfigurationProvider(XmlConfigurationSource)
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.XmlConfigurationProvider(Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: .ctor
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationProvider.cs
    startLine: 22
  assemblies:
  - Microsoft.Extensions.Configuration.Xml
  namespace: Microsoft.Extensions.Configuration.Xml
  summary: "\nInitializes a new instance with the specified source.\n"
  example: []
  syntax:
    content: public XmlConfigurationProvider(XmlConfigurationSource source)
    parameters:
    - id: source
      type: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
      description: The source settings.
    content.vb: Public Sub New(source As XmlConfigurationSource)
  overload: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load(System.IO.Stream)
  commentId: M:Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load(System.IO.Stream)
  id: Load(System.IO.Stream)
  parent: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider
  langs:
  - csharp
  - vb
  name: Load(Stream)
  nameWithType: XmlConfigurationProvider.Load(Stream)
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load(System.IO.Stream)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationProvider.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Load
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationProvider.cs
    startLine: 30
  assemblies:
  - Microsoft.Extensions.Configuration.Xml
  namespace: Microsoft.Extensions.Configuration.Xml
  summary: "\nLoads the XML data from a stream.\n"
  example: []
  syntax:
    content: public override void Load(Stream stream)
    parameters:
    - id: stream
      type: System.IO.Stream
      description: The stream to read.
    content.vb: Public Overrides Sub Load(stream As Stream)
  overload: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Extensions.Configuration.Xml
  commentId: N:Microsoft.Extensions.Configuration.Xml
  isExternal: false
  name: Microsoft.Extensions.Configuration.Xml
  nameWithType: Microsoft.Extensions.Configuration.Xml
  fullName: Microsoft.Extensions.Configuration.Xml
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.#ctor*
  commentId: Overload:Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.#ctor
  isExternal: false
  name: XmlConfigurationProvider
  nameWithType: XmlConfigurationProvider.XmlConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.XmlConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
  parent: Microsoft.Extensions.Configuration.Xml
  isExternal: false
  name: XmlConfigurationSource
  nameWithType: XmlConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource
- uid: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load*
  commentId: Overload:Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load
  isExternal: false
  name: Load
  nameWithType: XmlConfigurationProvider.Load
  fullName: Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load
- uid: System.IO.Stream
  commentId: T:System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.IO
  commentId: N:System.IO
  isExternal: false
  name: System.IO
  nameWithType: System.IO
  fullName: System.IO
shouldSkipMarkup: true
