### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.UserSecrets
  commentId: N:Microsoft.Extensions.Configuration.UserSecrets
  id: Microsoft.Extensions.Configuration.UserSecrets
  children:
  - Microsoft.Extensions.Configuration.UserSecrets.PathHelper
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.UserSecrets
  nameWithType: Microsoft.Extensions.Configuration.UserSecrets
  fullName: Microsoft.Extensions.Configuration.UserSecrets
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.UserSecrets
references:
- uid: Microsoft.Extensions.Configuration.UserSecrets.PathHelper
  commentId: T:Microsoft.Extensions.Configuration.UserSecrets.PathHelper
  isExternal: false
  name: PathHelper
  nameWithType: PathHelper
  fullName: Microsoft.Extensions.Configuration.UserSecrets.PathHelper
