### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
  id: EnvironmentVariablesConfigurationSource
  parent: Microsoft.Extensions.Configuration.EnvironmentVariables
  children:
  - Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build(IConfigurationBuilder)
  - Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Prefix
  langs:
  - csharp
  - vb
  name: EnvironmentVariablesConfigurationSource
  nameWithType: EnvironmentVariablesConfigurationSource
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: EnvironmentVariablesConfigurationSource
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationSource.cs
    startLine: 8
  assemblies:
  - Microsoft.Extensions.Configuration.EnvironmentVariables
  namespace: Microsoft.Extensions.Configuration.EnvironmentVariables
  summary: "\nRepresents environment variables as an <see cref=\"!:IConfigurationSource\"></see>.\n"
  example: []
  syntax:
    content: 'public class EnvironmentVariablesConfigurationSource : IConfigurationSource'
    content.vb: >-
      Public Class EnvironmentVariablesConfigurationSource
          Inherits IConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Prefix
  commentId: P:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Prefix
  id: Prefix
  parent: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
  langs:
  - csharp
  - vb
  name: Prefix
  nameWithType: EnvironmentVariablesConfigurationSource.Prefix
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Prefix
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Prefix
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationSource.cs
    startLine: 13
  assemblies:
  - Microsoft.Extensions.Configuration.EnvironmentVariables
  namespace: Microsoft.Extensions.Configuration.EnvironmentVariables
  summary: "\nA prefix used to filter environment variables.\n"
  example: []
  syntax:
    content: public string Prefix { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Prefix As String
  overload: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Prefix*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build(IConfigurationBuilder)
  commentId: M:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: EnvironmentVariablesConfigurationSource.Build(IConfigurationBuilder)
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationSource.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: Build
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationSource.cs
    startLine: 20
  assemblies:
  - Microsoft.Extensions.Configuration.EnvironmentVariables
  namespace: Microsoft.Extensions.Configuration.EnvironmentVariables
  summary: "\nBuilds the <xref href=\"Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider\" data-throw-if-not-resolved=\"false\"></xref> for this source.\n"
  example: []
  syntax:
    content: public IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see>.
    return:
      type: IConfigurationProvider
      description: A <xref href="Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider" data-throw-if-not-resolved="false"></xref>
    content.vb: Public Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables
  commentId: N:Microsoft.Extensions.Configuration.EnvironmentVariables
  isExternal: false
  name: Microsoft.Extensions.Configuration.EnvironmentVariables
  nameWithType: Microsoft.Extensions.Configuration.EnvironmentVariables
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Prefix*
  commentId: Overload:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Prefix
  isExternal: false
  name: Prefix
  nameWithType: EnvironmentVariablesConfigurationSource.Prefix
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Prefix
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
  isExternal: false
  name: EnvironmentVariablesConfigurationProvider
  nameWithType: EnvironmentVariablesConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider
- uid: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build*
  commentId: Overload:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build
  isExternal: false
  name: Build
  nameWithType: EnvironmentVariablesConfigurationSource.Build
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
shouldSkipMarkup: true
