### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider
  commentId: T:Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider
  id: CorsApplicationModelProvider
  parent: Microsoft.AspNetCore.Mvc.Cors.Internal
  children:
  - Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext)
  - Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext)
  - Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.Order
  langs:
  - csharp
  - vb
  name: CorsApplicationModelProvider
  nameWithType: CorsApplicationModelProvider
  fullName: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider
  type: Class
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsApplicationModelProvider.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: CorsApplicationModelProvider
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsApplicationModelProvider.cs
    startLine: 10
  assemblies:
  - Microsoft.AspNetCore.Mvc.Cors
  namespace: Microsoft.AspNetCore.Mvc.Cors.Internal
  syntax:
    content: 'public class CorsApplicationModelProvider : IApplicationModelProvider'
    content.vb: >-
      Public Class CorsApplicationModelProvider
          Inherits IApplicationModelProvider
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.Order
  commentId: P:Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.Order
  id: Order
  parent: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider
  langs:
  - csharp
  - vb
  name: Order
  nameWithType: CorsApplicationModelProvider.Order
  fullName: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.Order
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsApplicationModelProvider.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: Order
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsApplicationModelProvider.cs
    startLine: 12
  assemblies:
  - Microsoft.AspNetCore.Mvc.Cors
  namespace: Microsoft.AspNetCore.Mvc.Cors.Internal
  syntax:
    content: public int Order { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property Order As Integer
  overload: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.Order*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext)
  commentId: M:Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext)
  id: OnProvidersExecuted(ApplicationModelProviderContext)
  parent: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider
  langs:
  - csharp
  - vb
  name: OnProvidersExecuted(ApplicationModelProviderContext)
  nameWithType: CorsApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext)
  fullName: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsApplicationModelProvider.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: OnProvidersExecuted
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsApplicationModelProvider.cs
    startLine: 14
  assemblies:
  - Microsoft.AspNetCore.Mvc.Cors
  namespace: Microsoft.AspNetCore.Mvc.Cors.Internal
  syntax:
    content: public void OnProvidersExecuted(ApplicationModelProviderContext context)
    parameters:
    - id: context
      type: ApplicationModelProviderContext
    content.vb: Public Sub OnProvidersExecuted(context As ApplicationModelProviderContext)
  overload: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuted*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext)
  commentId: M:Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext)
  id: OnProvidersExecuting(ApplicationModelProviderContext)
  parent: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider
  langs:
  - csharp
  - vb
  name: OnProvidersExecuting(ApplicationModelProviderContext)
  nameWithType: CorsApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext)
  fullName: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsApplicationModelProvider.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: OnProvidersExecuting
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsApplicationModelProvider.cs
    startLine: 23
  assemblies:
  - Microsoft.AspNetCore.Mvc.Cors
  namespace: Microsoft.AspNetCore.Mvc.Cors.Internal
  syntax:
    content: public void OnProvidersExecuting(ApplicationModelProviderContext context)
    parameters:
    - id: context
      type: ApplicationModelProviderContext
    content.vb: Public Sub OnProvidersExecuting(context As ApplicationModelProviderContext)
  overload: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuting*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.AspNetCore.Mvc.Cors.Internal
  commentId: N:Microsoft.AspNetCore.Mvc.Cors.Internal
  isExternal: false
  name: Microsoft.AspNetCore.Mvc.Cors.Internal
  nameWithType: Microsoft.AspNetCore.Mvc.Cors.Internal
  fullName: Microsoft.AspNetCore.Mvc.Cors.Internal
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.Order*
  commentId: Overload:Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.Order
  isExternal: false
  name: Order
  nameWithType: CorsApplicationModelProvider.Order
  fullName: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.Order
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuted*
  commentId: Overload:Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuted
  isExternal: false
  name: OnProvidersExecuted
  nameWithType: CorsApplicationModelProvider.OnProvidersExecuted
  fullName: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuted
- uid: ApplicationModelProviderContext
  isExternal: true
  name: ApplicationModelProviderContext
  nameWithType: ApplicationModelProviderContext
  fullName: ApplicationModelProviderContext
- uid: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuting*
  commentId: Overload:Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuting
  isExternal: false
  name: OnProvidersExecuting
  nameWithType: CorsApplicationModelProvider.OnProvidersExecuting
  fullName: Microsoft.AspNetCore.Mvc.Cors.Internal.CorsApplicationModelProvider.OnProvidersExecuting
shouldSkipMarkup: true
