### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  commentId: T:Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  id: MemoryConfigurationBuilderExtensions
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder)
  - Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder,IEnumerable{KeyValuePair{System.String,System.String}})
  langs:
  - csharp
  - vb
  name: MemoryConfigurationBuilderExtensions
  nameWithType: MemoryConfigurationBuilderExtensions
  fullName: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/MemoryConfigurationBuilderExtensions.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: MemoryConfigurationBuilderExtensions
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/MemoryConfigurationBuilderExtensions.cs
    startLine: 12
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nIConfigurationBuilder extension methods for the MemoryConfigurationProvider.\n"
  example: []
  syntax:
    content: 'public static class MemoryConfigurationBuilderExtensions : object'
    content.vb: >-
      Public Module MemoryConfigurationBuilderExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder)
  commentId: M:Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder)
  id: AddInMemoryCollection(IConfigurationBuilder)
  isExtensionMethod: true
  parent: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  langs:
  - csharp
  - vb
  name: AddInMemoryCollection(IConfigurationBuilder)
  nameWithType: MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder)
  fullName: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/MemoryConfigurationBuilderExtensions.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: AddInMemoryCollection
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/MemoryConfigurationBuilderExtensions.cs
    startLine: 19
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nAdds the memory configuration provider to <code data-dev-comment-type=\"paramref\">configurationBuilder</code>.\n"
  example: []
  syntax:
    content: public static IConfigurationBuilder AddInMemoryCollection(this IConfigurationBuilder configurationBuilder)
    parameters:
    - id: configurationBuilder
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see> to add to.
    return:
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see>.
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddInMemoryCollection(configurationBuilder As IConfigurationBuilder) As IConfigurationBuilder
  overload: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder,IEnumerable{KeyValuePair{System.String,System.String}})
  commentId: M:Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder,IEnumerable{KeyValuePair{System.String,System.String}})
  id: AddInMemoryCollection(IConfigurationBuilder,IEnumerable{KeyValuePair{System.String,System.String}})
  isExtensionMethod: true
  parent: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  langs:
  - csharp
  - vb
  name: AddInMemoryCollection(IConfigurationBuilder, IEnumerable<KeyValuePair<String, String>>)
  nameWithType: MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder, IEnumerable<KeyValuePair<String, String>>)
  fullName: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder, IEnumerable<KeyValuePair<System.String, System.String>>)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/MemoryConfigurationBuilderExtensions.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: AddInMemoryCollection
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/MemoryConfigurationBuilderExtensions.cs
    startLine: 36
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nAdds the memory configuration provider to <code data-dev-comment-type=\"paramref\">configurationBuilder</code>.\n"
  example: []
  syntax:
    content: public static IConfigurationBuilder AddInMemoryCollection(this IConfigurationBuilder configurationBuilder, IEnumerable<KeyValuePair<string, string>> initialData)
    parameters:
    - id: configurationBuilder
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see> to add to.
    - id: initialData
      type: IEnumerable{KeyValuePair{System.String,System.String}}
      description: The data to add to memory configuration provider.
    return:
      type: IConfigurationBuilder
      description: The <see cref="!:IConfigurationBuilder"></see>.
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddInMemoryCollection(configurationBuilder As IConfigurationBuilder, initialData As IEnumerable(Of KeyValuePair(Of String, String))) As IConfigurationBuilder
  overload: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection*
  nameWithType.vb: MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder, IEnumerable(Of KeyValuePair(Of String, String)))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection(IConfigurationBuilder, IEnumerable(Of KeyValuePair(Of System.String, System.String)))
  name.vb: AddInMemoryCollection(IConfigurationBuilder, IEnumerable(Of KeyValuePair(Of String, String)))
references:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection*
  commentId: Overload:Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection
  isExternal: false
  name: AddInMemoryCollection
  nameWithType: MemoryConfigurationBuilderExtensions.AddInMemoryCollection
  fullName: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.AddInMemoryCollection
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IEnumerable{KeyValuePair{System.String,System.String}}
  commentId: '!:IEnumerable{KeyValuePair{System.String,System.String}}'
  definition: IEnumerable`1
  name: IEnumerable<KeyValuePair<String, String>>
  nameWithType: IEnumerable<KeyValuePair<String, String>>
  fullName: IEnumerable<KeyValuePair<System.String, System.String>>
  nameWithType.vb: IEnumerable(Of KeyValuePair(Of String, String))
  fullName.vb: IEnumerable(Of KeyValuePair(Of System.String, System.String))
  name.vb: IEnumerable(Of KeyValuePair(Of String, String))
  spec.csharp:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: KeyValuePair`2
    name: KeyValuePair
    nameWithType: KeyValuePair
    fullName: KeyValuePair
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: KeyValuePair`2
    name: KeyValuePair
    nameWithType: KeyValuePair
    fullName: KeyValuePair
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: IEnumerable`1
  isExternal: true
  name: IEnumerable<>
  nameWithType: IEnumerable<>
  fullName: IEnumerable<>
  nameWithType.vb: IEnumerable(Of )
  fullName.vb: IEnumerable(Of )
  name.vb: IEnumerable(Of )
  spec.csharp:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
shouldSkipMarkup: true
