### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationReloadToken
  id: ConfigurationReloadToken
  parent: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.ConfigurationReloadToken.ActiveChangeCallbacks
  - Microsoft.Extensions.Configuration.ConfigurationReloadToken.HasChanged
  - Microsoft.Extensions.Configuration.ConfigurationReloadToken.OnReload
  - Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback(Action{System.Object},System.Object)
  langs:
  - csharp
  - vb
  name: ConfigurationReloadToken
  nameWithType: ConfigurationReloadToken
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken
  type: Class
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: ConfigurationReloadToken
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
    startLine: 12
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nImplements <see cref=\"!:IChangeToken\"></see>\n"
  example: []
  syntax:
    content: 'public class ConfigurationReloadToken : IChangeToken'
    content.vb: >-
      Public Class ConfigurationReloadToken
          Inherits IChangeToken
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken.ActiveChangeCallbacks
  commentId: P:Microsoft.Extensions.Configuration.ConfigurationReloadToken.ActiveChangeCallbacks
  id: ActiveChangeCallbacks
  parent: Microsoft.Extensions.Configuration.ConfigurationReloadToken
  langs:
  - csharp
  - vb
  name: ActiveChangeCallbacks
  nameWithType: ConfigurationReloadToken.ActiveChangeCallbacks
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken.ActiveChangeCallbacks
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: ActiveChangeCallbacks
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
    startLine: 19
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nIndicates if this token will proactively raise callbacks. Callbacks are still guaranteed to be invoked, eventually.\n"
  example: []
  syntax:
    content: public bool ActiveChangeCallbacks { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property ActiveChangeCallbacks As Boolean
  overload: Microsoft.Extensions.Configuration.ConfigurationReloadToken.ActiveChangeCallbacks*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken.HasChanged
  commentId: P:Microsoft.Extensions.Configuration.ConfigurationReloadToken.HasChanged
  id: HasChanged
  parent: Microsoft.Extensions.Configuration.ConfigurationReloadToken
  langs:
  - csharp
  - vb
  name: HasChanged
  nameWithType: ConfigurationReloadToken.HasChanged
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken.HasChanged
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: HasChanged
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
    startLine: 24
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nGets a value that indicates if a change has occured.\n"
  example: []
  syntax:
    content: public bool HasChanged { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property HasChanged As Boolean
  overload: Microsoft.Extensions.Configuration.ConfigurationReloadToken.HasChanged*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback(Action{System.Object},System.Object)
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback(Action{System.Object},System.Object)
  id: RegisterChangeCallback(Action{System.Object},System.Object)
  parent: Microsoft.Extensions.Configuration.ConfigurationReloadToken
  langs:
  - csharp
  - vb
  name: RegisterChangeCallback(Action<Object>, Object)
  nameWithType: ConfigurationReloadToken.RegisterChangeCallback(Action<Object>, Object)
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback(Action<System.Object>, System.Object)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: RegisterChangeCallback
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
    startLine: 33
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nRegisters for a callback that will be invoked when the entry has changed. Microsoft.Extensions.Primitives.IChangeToken.HasChanged\nMUST be set before the callback is invoked.\n"
  example: []
  syntax:
    content: public IDisposable RegisterChangeCallback(Action<object> callback, object state)
    parameters:
    - id: callback
      type: Action{System.Object}
      description: The callback to invoke.
    - id: state
      type: System.Object
      description: State to be passed into the callback.
    return:
      type: IDisposable
      description: ''
    content.vb: Public Function RegisterChangeCallback(callback As Action(Of Object), state As Object) As IDisposable
  overload: Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback*
  nameWithType.vb: ConfigurationReloadToken.RegisterChangeCallback(Action(Of Object), Object)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback(Action(Of System.Object), System.Object)
  name.vb: RegisterChangeCallback(Action(Of Object), Object)
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken.OnReload
  commentId: M:Microsoft.Extensions.Configuration.ConfigurationReloadToken.OnReload
  id: OnReload
  parent: Microsoft.Extensions.Configuration.ConfigurationReloadToken
  langs:
  - csharp
  - vb
  name: OnReload()
  nameWithType: ConfigurationReloadToken.OnReload()
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken.OnReload()
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
      branch: master
      repo: https://github.com/aspnet/Configuration.git
    id: OnReload
    path: ../aspnet/Configuration/src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
    startLine: 38
  assemblies:
  - Microsoft.Extensions.Configuration
  namespace: Microsoft.Extensions.Configuration
  summary: "\nUsed to trigger the change token when a reload occurs.\n"
  example: []
  syntax:
    content: public void OnReload()
    content.vb: Public Sub OnReload
  overload: Microsoft.Extensions.Configuration.ConfigurationReloadToken.OnReload*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken.ActiveChangeCallbacks*
  commentId: Overload:Microsoft.Extensions.Configuration.ConfigurationReloadToken.ActiveChangeCallbacks
  isExternal: false
  name: ActiveChangeCallbacks
  nameWithType: ConfigurationReloadToken.ActiveChangeCallbacks
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken.ActiveChangeCallbacks
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken.HasChanged*
  commentId: Overload:Microsoft.Extensions.Configuration.ConfigurationReloadToken.HasChanged
  isExternal: false
  name: HasChanged
  nameWithType: ConfigurationReloadToken.HasChanged
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken.HasChanged
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback*
  commentId: Overload:Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback
  isExternal: false
  name: RegisterChangeCallback
  nameWithType: ConfigurationReloadToken.RegisterChangeCallback
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken.RegisterChangeCallback
- uid: Action{System.Object}
  commentId: '!:Action{System.Object}'
  definition: Action`1
  name: Action<Object>
  nameWithType: Action<Object>
  fullName: Action<System.Object>
  nameWithType.vb: Action(Of Object)
  fullName.vb: Action(Of System.Object)
  name.vb: Action(Of Object)
  spec.csharp:
  - uid: Action`1
    name: Action
    nameWithType: Action
    fullName: Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Action`1
    name: Action
    nameWithType: Action
    fullName: Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: IDisposable
  isExternal: true
  name: IDisposable
  nameWithType: IDisposable
  fullName: IDisposable
- uid: Action`1
  isExternal: true
  name: Action<>
  nameWithType: Action<>
  fullName: Action<>
  nameWithType.vb: Action(Of )
  fullName.vb: Action(Of )
  name.vb: Action(Of )
  spec.csharp:
  - uid: Action`1
    name: Action
    nameWithType: Action
    fullName: Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Action`1
    name: Action
    nameWithType: Action
    fullName: Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken.OnReload*
  commentId: Overload:Microsoft.Extensions.Configuration.ConfigurationReloadToken.OnReload
  isExternal: false
  name: OnReload
  nameWithType: ConfigurationReloadToken.OnReload
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken.OnReload
shouldSkipMarkup: true
